export const problems = [
  {
    problem_order: 1,
    problem_slug: 'contains-duplicate',
    problem_no: 217,
    topic: 'arrays-hashing',
    difficulty: 'Easy',
  },
  {
    problem_order: 2,
    problem_slug: 'intersection-of-two-arrays',
    problem_no: 349,
    topic: 'arrays-hashing',
    difficulty: 'Easy',
  },
  {
    problem_order: 3,
    problem_slug: 'majority-element',
    problem_no: 169,
    topic: 'arrays-hashing',
    difficulty: 'Easy',
  },
  {
    problem_order: 4,
    problem_slug: 'find-the-duplicate-number',
    problem_no: 287,
    topic: 'arrays-hashing',
    difficulty: 'Easy',
  },
  {
    problem_order: 5,
    problem_slug: '3sum',
    problem_no: 15,
    topic: 'arrays-hashing',
    difficulty: 'Medium',
  },
  {
    problem_order: 6,
    problem_slug: 'group-anagrams',
    problem_no: 49,
    topic: 'arrays-hashing',
    difficulty: 'Medium',
  },
  {
    problem_order: 7,
    problem_slug: 'subarray-sum-equals-k',
    problem_no: 560,
    topic: 'arrays-hashing',
    difficulty: 'Medium',
  },
  {
    problem_order: 8,
    problem_slug: 'top-k-frequent-elements',
    problem_no: 347,
    topic: 'arrays-hashing',
    difficulty: 'Medium',
  },
  {
    problem_order: 9,
    problem_slug: 'product-of-array-except-self',
    problem_no: 238,
    topic: 'arrays-hashing',
    difficulty: 'Medium',
  },
  {
    problem_order: 10,
    problem_slug: 'valid-palindrome',
    problem_no: 125,
    topic: 'two-pointers',
    difficulty: 'Easy',
  },
  {
    problem_order: 11,
    problem_slug: 'two-sum-ii-input-array-is-sorted',
    problem_no: 167,
    topic: 'two-pointers',
    difficulty: 'Medium',
  },
  {
    problem_order: 12,
    problem_slug: '3sum',
    problem_no: 15,
    topic: 'two-pointers',
    difficulty: 'Medium',
  },
  {
    problem_order: 13,
    problem_slug: 'container-with-most-water',
    problem_no: 11,
    topic: 'two-pointers',
    difficulty: 'Medium',
  },
  {
    problem_order: 14,
    problem_slug: 'contains-duplicate',
    problem_no: 217,
    topic: 'sliding-window',
    difficulty: 'Easy',
  },
  {
    problem_order: 15,
    problem_slug: 'best-time-to-buy-and-sell-stock',
    problem_no: 121,
    topic: 'sliding-window',
    difficulty: 'Easy',
  },
  {
    problem_order: 16,
    problem_slug: 'longest-substring-without-repeating-characters',
    problem_no: 3,
    topic: 'sliding-window',
    difficulty: 'Medium',
  },
  {
    problem_order: 17,
    problem_slug: 'longest-repeating-character-replacement',
    problem_no: 424,
    topic: 'sliding-window',
    difficulty: 'Medium',
  },
  {
    problem_order: 18,
    problem_slug: 'permutation-in-string',
    problem_no: 567,
    topic: 'sliding-window',
    difficulty: 'Medium',
  },
  {
    problem_order: 19,
    problem_slug: 'minimum-size-subarray-sum',
    problem_no: 209,
    topic: 'sliding-window',
    difficulty: 'Medium',
  },
  {
    problem_order: 20,
    problem_slug: 'valid-parentheses',
    problem_no: 20,
    topic: 'stack',
    difficulty: 'Easy',
  },
  {
    problem_order: 21,
    problem_slug: 'min-stack',
    problem_no: 155,
    topic: 'stack',
    difficulty: 'Easy',
  },
  {
    problem_order: 22,
    problem_slug: 'evaluate-reverse-polish-notation',
    problem_no: 150,
    topic: 'stack',
    difficulty: 'Medium',
  },
  {
    problem_order: 23,
    problem_slug: 'generate-parentheses',
    problem_no: 22,
    topic: 'stack',
    difficulty: 'Medium',
  },
  {
    problem_order: 24,
    problem_slug: 'daily-temperatures',
    problem_no: 739,
    topic: 'stack',
    difficulty: 'Medium',
  },
  {
    problem_order: 25,
    problem_slug: 'car-fleet',
    problem_no: 853,
    topic: 'stack',
    difficulty: 'Medium',
  },
  {
    problem_order: 26,
    problem_slug: 'binary-search',
    problem_no: 704,
    topic: 'binary-search',
    difficulty: 'Easy',
  },
  {
    problem_order: 27,
    problem_slug: 'search-a-2d-matrix',
    problem_no: 74,
    topic: 'binary-search',
    difficulty: 'Medium',
  },
  {
    problem_order: 28,
    problem_slug: 'koko-eating-bananas',
    problem_no: 875,
    topic: 'binary-search',
    difficulty: 'Medium',
  },
  {
    problem_order: 29,
    problem_slug: 'search-in-rotated-sorted-array',
    problem_no: 33,
    topic: 'binary-search',
    difficulty: 'Medium',
  },
  {
    problem_order: 30,
    problem_slug: 'find-minimum-in-rotated-sorted-array',
    problem_no: 153,
    topic: 'binary-search',
    difficulty: 'Medium',
  },
  {
    problem_order: 31,
    problem_slug: 'time-based-key-value-store',
    problem_no: 981,
    topic: 'binary-search',
    difficulty: 'Medium',
  },
  {
    problem_order: 32,
    problem_slug: 'median-of-two-sorted-arrays',
    problem_no: 4,
    topic: 'binary-search',
    difficulty: 'Hard',
  },
  {
    problem_order: 33,
    problem_slug: 'reverse-linked-list',
    problem_no: 206,
    topic: 'linked-list',
    difficulty: 'Easy',
  },
  {
    problem_order: 34,
    problem_slug: 'merge-two-sorted-lists',
    problem_no: 21,
    topic: 'linked-list',
    difficulty: 'Easy',
  },
  {
    problem_order: 35,
    problem_slug: 'linked-list-cycle',
    problem_no: 141,
    topic: 'linked-list',
    difficulty: 'Easy',
  },
  {
    problem_order: 36,
    problem_slug: 'reorder-list',
    problem_no: 143,
    topic: 'linked-list',
    difficulty: 'Medium',
  },
  {
    problem_order: 37,
    problem_slug: 'remove-nth-node-from-end-of-list',
    problem_no: 19,
    topic: 'linked-list',
    difficulty: 'Medium',
  },
  {
    problem_order: 38,
    problem_slug: 'copy-list-with-random-pointer',
    problem_no: 138,
    topic: 'linked-list',
    difficulty: 'Medium',
  },
  {
    problem_order: 39,
    problem_slug: 'add-two-numbers',
    problem_no: 2,
    topic: 'linked-list',
    difficulty: 'Medium',
  },
  {
    problem_order: 40,
    problem_slug: 'find-the-duplicate-number',
    problem_no: 287,
    topic: 'linked-list',
    difficulty: 'Medium',
  },
  {
    problem_order: 41,
    problem_slug: 'lru-cache',
    problem_no: 146,
    topic: 'linked-list',
    difficulty: 'Medium',
  },
  {
    problem_order: 42,
    problem_slug: 'merge-k-sorted-lists',
    problem_no: 23,
    topic: 'linked-list',
    difficulty: 'Hard',
  },
  {
    problem_order: 43,
    problem_slug: 'reverse-nodes-in-k-group',
    problem_no: 25,
    topic: 'linked-list',
    difficulty: 'Hard',
  },
  {
    problem_order: 44,
    problem_slug: 'fibonacci-number',
    problem_no: 509,
    topic: 'recursion',
    difficulty: 'Easy',
  },
  {
    problem_order: 45,
    problem_slug: 'power-of-two',
    problem_no: 231,
    topic: 'recursion',
    difficulty: 'Easy',
  },
  {
    problem_order: 46,
    problem_slug: 'subsets',
    problem_no: 78,
    topic: 'recursion',
    difficulty: 'Medium',
  },
  {
    problem_order: 47,
    problem_slug: 'combination-sum',
    problem_no: 39,
    topic: 'recursion',
    difficulty: 'Medium',
  },
  {
    problem_order: 48,
    problem_slug: 'permutations',
    problem_no: 46,
    topic: 'recursion',
    difficulty: 'Medium',
  },
  {
    problem_order: 49,
    problem_slug: 'subsets-ii',
    problem_no: 90,
    topic: 'recursion',
    difficulty: 'Medium',
  },
  {
    problem_order: 50,
    problem_slug: 'combination-sum-ii',
    problem_no: 40,
    topic: 'recursion',
    difficulty: 'Medium',
  },
  {
    problem_order: 51,
    problem_slug: 'word-search',
    problem_no: 79,
    topic: 'recursion',
    difficulty: 'Medium',
  },
  {
    problem_order: 52,
    problem_slug: 'palindrome-partitioning',
    problem_no: 131,
    topic: 'recursion',
    difficulty: 'Medium',
  },
  {
    problem_order: 53,
    problem_slug: 'letter-combinations-of-a-phone-number',
    problem_no: 17,
    topic: 'recursion',
    difficulty: 'Medium',
  },
  {
    problem_order: 54,
    problem_slug: 'n-queens',
    problem_no: 51,
    topic: 'recursion',
    difficulty: 'Hard',
  },
  {
    problem_order: 55,
    problem_slug: 'invert-binary-tree',
    problem_no: 226,
    topic: 'trees',
    difficulty: 'Easy',
  },
  {
    problem_order: 56,
    problem_slug: 'maximum-depth-of-binary-tree',
    problem_no: 104,
    topic: 'trees',
    difficulty: 'Easy',
  },
  {
    problem_order: 57,
    problem_slug: 'diameter-of-binary-tree',
    problem_no: 543,
    topic: 'trees',
    difficulty: 'Easy',
  },
  {
    problem_order: 58,
    problem_slug: 'balanced-binary-tree',
    problem_no: 110,
    topic: 'trees',
    difficulty: 'Easy',
  },
  {
    problem_order: 59,
    problem_slug: 'same-tree',
    problem_no: 100,
    topic: 'trees',
    difficulty: 'Easy',
  },
  {
    problem_order: 60,
    problem_slug: 'subtree-of-another-tree',
    problem_no: 572,
    topic: 'trees',
    difficulty: 'Easy',
  },
  {
    problem_order: 61,
    problem_slug: 'lowest-common-ancestor-of-a-binary-search-tree',
    problem_no: 235,
    topic: 'trees',
    difficulty: 'Easy',
  },
  {
    problem_order: 62,
    problem_slug: 'binary-tree-level-order-traversal',
    problem_no: 102,
    topic: 'trees',
    difficulty: 'Medium',
  },
  {
    problem_order: 63,
    problem_slug: 'binary-tree-right-side-view',
    problem_no: 199,
    topic: 'trees',
    difficulty: 'Medium',
  },
  {
    problem_order: 64,
    problem_slug: 'count-good-nodes-in-binary-tree',
    problem_no: 1448,
    topic: 'trees',
    difficulty: 'Medium',
  },
  {
    problem_order: 65,
    problem_slug: 'validate-binary-search-tree',
    problem_no: 98,
    topic: 'trees',
    difficulty: 'Medium',
  },
  {
    problem_order: 66,
    problem_slug: 'kth-smallest-element-in-a-bst',
    problem_no: 230,
    topic: 'trees',
    difficulty: 'Medium',
  },
  {
    problem_order: 67,
    problem_slug: 'construct-binary-tree-from-preorder-and-inorder-traversal',
    problem_no: 105,
    topic: 'trees',
    difficulty: 'Medium',
  },
  {
    problem_order: 68,
    problem_slug: 'binary-tree-maximum-path-sum',
    problem_no: 124,
    topic: 'trees',
    difficulty: 'Hard',
  },
  {
    problem_order: 69,
    problem_slug: 'longest-common-prefix',
    problem_no: 14,
    topic: 'tries',
    difficulty: 'Easy',
  },
  {
    problem_order: 70,
    problem_slug: 'implement-trie-prefix-tree',
    problem_no: 208,
    topic: 'tries',
    difficulty: 'Medium',
  },
  {
    problem_order: 71,
    problem_slug: 'design-add-and-search-words-data-structure',
    problem_no: 211,
    topic: 'tries',
    difficulty: 'Medium',
  },
  {
    problem_order: 72,
    problem_slug: 'word-search-ii',
    problem_no: 212,
    topic: 'tries',
    difficulty: 'Hard',
  },
  {
    problem_order: 73,
    problem_slug: 'kth-largest-element-in-a-stream',
    problem_no: 703,
    topic: 'heap-priority-queue',
    difficulty: 'Easy',
  },
  {
    problem_order: 74,
    problem_slug: 'last-stone-weight',
    problem_no: 1046,
    topic: 'heap-priority-queue',
    difficulty: 'Easy',
  },
  {
    problem_order: 75,
    problem_slug: 'k-closest-points-to-origin',
    problem_no: 973,
    topic: 'heap-priority-queue',
    difficulty: 'Medium',
  },
  {
    problem_order: 76,
    problem_slug: 'kth-largest-element-in-an-array',
    problem_no: 215,
    topic: 'heap-priority-queue',
    difficulty: 'Medium',
  },
  {
    problem_order: 77,
    problem_slug: 'task-scheduler',
    problem_no: 621,
    topic: 'heap-priority-queue',
    difficulty: 'Medium',
  },
  {
    problem_order: 78,
    problem_slug: 'design-twitter',
    problem_no: 355,
    topic: 'heap-priority-queue',
    difficulty: 'Medium',
  },
  {
    problem_order: 79,
    problem_slug: 'find-median-from-data-stream',
    problem_no: 295,
    topic: 'heap-priority-queue',
    difficulty: 'Hard',
  },
  {
    problem_order: 80,
    problem_slug: 'number-of-islands',
    problem_no: 200,
    topic: 'graphs',
    difficulty: 'Medium',
  },
  {
    problem_order: 81,
    problem_slug: 'clone-graph',
    problem_no: 133,
    topic: 'graphs',
    difficulty: 'Medium',
  },
  {
    problem_order: 82,
    problem_slug: 'max-area-of-island',
    problem_no: 695,
    topic: 'graphs',
    difficulty: 'Medium',
  },
  {
    problem_order: 83,
    problem_slug: 'pacific-atlantic-water-flow',
    problem_no: 417,
    topic: 'graphs',
    difficulty: 'Medium',
  },
  {
    problem_order: 84,
    problem_slug: 'surrounded-regions',
    problem_no: 130,
    topic: 'graphs',
    difficulty: 'Medium',
  },
  {
    problem_order: 85,
    problem_slug: 'rotting-oranges',
    problem_no: 994,
    topic: 'graphs',
    difficulty: 'Medium',
  },
  {
    problem_order: 86,
    problem_slug: 'walls-and-gates',
    problem_no: 286,
    topic: 'graphs',
    difficulty: 'Medium',
  },
  {
    problem_order: 87,
    problem_slug: 'course-schedule',
    problem_no: 207,
    topic: 'graphs',
    difficulty: 'Medium',
  },
  {
    problem_order: 88,
    problem_slug: 'course-schedule-ii',
    problem_no: 210,
    topic: 'graphs',
    difficulty: 'Medium',
  },
  {
    problem_order: 89,
    problem_slug: 'redundant-connection',
    problem_no: 684,
    topic: 'graphs',
    difficulty: 'Medium',
  },
  {
    problem_order: 90,
    problem_slug: 'number-of-connected-components-in-an-undirected-graph',
    problem_no: 323,
    topic: 'graphs',
    difficulty: 'Medium',
  },
  {
    problem_order: 91,
    problem_slug: 'graph-valid-tree',
    problem_no: 261,
    topic: 'graphs',
    difficulty: 'Medium',
  },
  {
    problem_order: 92,
    problem_slug: 'word-ladder',
    problem_no: 127,
    topic: 'graphs',
    difficulty: 'Hard',
  },
  {
    problem_order: 93,
    problem_slug: 'climbing-stairs',
    problem_no: 70,
    topic: '1d-dp',
    difficulty: 'Easy',
  },
  {
    problem_order: 94,
    problem_slug: 'min-cost-climbing-stairs',
    problem_no: 746,
    topic: '1d-dp',
    difficulty: 'Easy',
  },
  {
    problem_order: 95,
    problem_slug: 'house-robber',
    problem_no: 198,
    topic: '1d-dp',
    difficulty: 'Medium',
  },
  {
    problem_order: 96,
    problem_slug: 'house-robber-ii',
    problem_no: 213,
    topic: '1d-dp',
    difficulty: 'Medium',
  },
  {
    problem_order: 97,
    problem_slug: 'longest-palindromic-substring',
    problem_no: 5,
    topic: '1d-dp',
    difficulty: 'Medium',
  },
  {
    problem_order: 98,
    problem_slug: 'palindromic-substrings',
    problem_no: 647,
    topic: '1d-dp',
    difficulty: 'Medium',
  },
  {
    problem_order: 99,
    problem_slug: 'decode-ways',
    problem_no: 91,
    topic: '1d-dp',
    difficulty: 'Medium',
  },
  {
    problem_order: 100,
    problem_slug: 'coin-change',
    problem_no: 322,
    topic: '1d-dp',
    difficulty: 'Medium',
  },
  {
    problem_order: 101,
    problem_slug: 'maximum-product-subarray',
    problem_no: 152,
    topic: '1d-dp',
    difficulty: 'Medium',
  },
  {
    problem_order: 102,
    problem_slug: 'word-break',
    problem_no: 139,
    topic: '1d-dp',
    difficulty: 'Medium',
  },
  {
    problem_order: 103,
    problem_slug: 'longest-increasing-subsequence',
    problem_no: 300,
    topic: '1d-dp',
    difficulty: 'Medium',
  },
  {
    problem_order: 104,
    problem_slug: 'partition-equal-subset-sum',
    problem_no: 416,
    topic: '1d-dp',
    difficulty: 'Medium',
  },
  {
    problem_order: 105,
    problem_slug: 'unique-paths',
    problem_no: 62,
    topic: '2d-dp',
    difficulty: 'Medium',
  },
  {
    problem_order: 106,
    problem_slug: 'longest-common-subsequence',
    problem_no: 1143,
    topic: '2d-dp',
    difficulty: 'Medium',
  },
  {
    problem_order: 107,
    problem_slug: 'best-time-to-buy-and-sell-stock-with-cooldown',
    problem_no: 309,
    topic: '2d-dp',
    difficulty: 'Medium',
  },
  {
    problem_order: 108,
    problem_slug: 'coin-change-2',
    problem_no: 518,
    topic: '2d-dp',
    difficulty: 'Medium',
  },
  {
    problem_order: 109,
    problem_slug: 'target-sum',
    problem_no: 494,
    topic: '2d-dp',
    difficulty: 'Medium',
  },
  {
    problem_order: 110,
    problem_slug: 'interleaving-string',
    problem_no: 97,
    topic: '2d-dp',
    difficulty: 'Medium',
  },
  {
    problem_order: 111,
    problem_slug: 'longest-increasing-path-in-a-matrix',
    problem_no: 329,
    topic: '2d-dp',
    difficulty: 'Hard',
  },
  {
    problem_order: 112,
    problem_slug: 'distinct-subsequences',
    problem_no: 115,
    topic: '2d-dp',
    difficulty: 'Hard',
  },
  {
    problem_order: 113,
    problem_slug: 'edit-distance',
    problem_no: 72,
    topic: '2d-dp',
    difficulty: 'Hard',
  },
  {
    problem_order: 114,
    problem_slug: 'burst-balloons',
    problem_no: 312,
    topic: '2d-dp',
    difficulty: 'Hard',
  },
  {
    problem_order: 115,
    problem_slug: 'regular-expression-matching',
    problem_no: 10,
    topic: '2d-dp',
    difficulty: 'Hard',
  },
  {
    problem_order: 116,
    problem_slug: 'single-number',
    problem_no: 136,
    topic: 'bit-manipulation',
    difficulty: 'Easy',
  },
  {
    problem_order: 117,
    problem_slug: 'number-of-1-bits',
    problem_no: 191,
    topic: 'bit-manipulation',
    difficulty: 'Easy',
  },
  {
    problem_order: 118,
    problem_slug: 'counting-bits',
    problem_no: 338,
    topic: 'bit-manipulation',
    difficulty: 'Easy',
  },
  {
    problem_order: 119,
    problem_slug: 'reverse-bits',
    problem_no: 190,
    topic: 'bit-manipulation',
    difficulty: 'Easy',
  },
  {
    problem_order: 120,
    problem_slug: 'missing-number',
    problem_no: 268,
    topic: 'bit-manipulation',
    difficulty: 'Easy',
  },
  {
    problem_order: 121,
    problem_slug: 'sum-of-two-integers',
    problem_no: 371,
    topic: 'bit-manipulation',
    difficulty: 'Medium',
  },
  {
    problem_order: 122,
    problem_slug: 'reverse-integer',
    problem_no: 7,
    topic: 'bit-manipulation',
    difficulty: 'Medium',
  },
]
