-- Add official LeetCode study-plan roadmaps and their problem memberships.

INSERT INTO "RoadmapCatalog" ("id", "key", "slug", "title", "description", "source", "sortOrder", "updatedAt")
VALUES
  ('roadmap_top_interview_150', 'TOP_INTERVIEW_150', 'top-interview-150', 'Top Interview 150', '150 original and classic interview questions', 'LEETCODE', 40, CURRENT_TIMESTAMP),
  ('roadmap_top_sql_50', 'TOP_SQL_50', 'top-sql-50', 'SQL 50', '50 essential SQL interview questions', 'LEETCODE', 50, CURRENT_TIMESTAMP),
  ('roadmap_dynamic_programming', 'DYNAMIC_PROGRAMMING', 'dynamic-programming', 'Dynamic Programming', 'Essential dynamic programming patterns', 'LEETCODE', 60, CURRENT_TIMESTAMP),
  ('roadmap_js_30', 'JS_30', '30-days-of-javascript', '30 Days of JavaScript', 'JavaScript basics and fluency problems', 'LEETCODE', 70, CURRENT_TIMESTAMP)
ON CONFLICT ("key") DO UPDATE SET
  "slug" = EXCLUDED."slug",
  "title" = EXCLUDED."title",
  "description" = EXCLUDED."description",
  "source" = EXCLUDED."source",
  "sortOrder" = EXCLUDED."sortOrder",
  "isActive" = true,
  "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "Problem" ("id", "slug", "title", "difficulty", "topic", "roadmapIndex", "leetcodeId", "isPremium", "source")
VALUES
  ('problem_lc_1', 'two-sum', 'Two Sum', 'EASY', 'Hashmap', 100001, 1, false, 'NEETCODE'),
  ('problem_lc_2', 'add-two-numbers', 'Add Two Numbers', 'MEDIUM', 'Linked List', 100002, 2, false, 'NEETCODE'),
  ('problem_lc_3', 'longest-substring-without-repeating-characters', 'Longest Substring Without Repeating Characters', 'MEDIUM', 'Sliding Window', 100003, 3, false, 'NEETCODE'),
  ('problem_lc_4', 'median-of-two-sorted-arrays', 'Median of Two Sorted Arrays', 'HARD', 'Binary Search', 100004, 4, false, 'NEETCODE'),
  ('problem_lc_5', 'longest-palindromic-substring', 'Longest Palindromic Substring', 'MEDIUM', 'On Strings', 100005, 5, false, 'NEETCODE'),
  ('problem_lc_6', 'zigzag-conversion', 'Zigzag Conversion', 'MEDIUM', 'Array / String', 100006, 6, false, 'NEETCODE'),
  ('problem_lc_9', 'palindrome-number', 'Palindrome Number', 'EASY', 'Math', 100009, 9, false, 'NEETCODE'),
  ('problem_lc_11', 'container-with-most-water', 'Container With Most Water', 'MEDIUM', 'Two Pointers', 100011, 11, false, 'NEETCODE'),
  ('problem_lc_12', 'integer-to-roman', 'Integer to Roman', 'MEDIUM', 'Array / String', 100012, 12, false, 'NEETCODE'),
  ('problem_lc_13', 'roman-to-integer', 'Roman to Integer', 'EASY', 'Array / String', 100013, 13, false, 'NEETCODE'),
  ('problem_lc_14', 'longest-common-prefix', 'Longest Common Prefix', 'EASY', 'Array / String', 100014, 14, false, 'NEETCODE'),
  ('problem_lc_15', '3sum', '3Sum', 'MEDIUM', 'Two Pointers', 100015, 15, false, 'NEETCODE'),
  ('problem_lc_17', 'letter-combinations-of-a-phone-number', 'Letter Combinations of a Phone Number', 'MEDIUM', 'Backtracking', 100017, 17, false, 'NEETCODE'),
  ('problem_lc_19', 'remove-nth-node-from-end-of-list', 'Remove Nth Node From End of List', 'MEDIUM', 'Linked List', 100019, 19, false, 'NEETCODE'),
  ('problem_lc_20', 'valid-parentheses', 'Valid Parentheses', 'EASY', 'Stack', 100020, 20, false, 'NEETCODE'),
  ('problem_lc_21', 'merge-two-sorted-lists', 'Merge Two Sorted Lists', 'EASY', 'Linked List', 100021, 21, false, 'NEETCODE'),
  ('problem_lc_22', 'generate-parentheses', 'Generate Parentheses', 'MEDIUM', 'Backtracking', 100022, 22, false, 'NEETCODE'),
  ('problem_lc_23', 'merge-k-sorted-lists', 'Merge k Sorted Lists', 'HARD', 'Divide & Conquer', 100023, 23, false, 'NEETCODE'),
  ('problem_lc_25', 'reverse-nodes-in-k-group', 'Reverse Nodes in k-Group', 'HARD', 'Linked List', 100025, 25, false, 'NEETCODE'),
  ('problem_lc_26', 'remove-duplicates-from-sorted-array', 'Remove Duplicates from Sorted Array', 'EASY', 'Array / String', 100026, 26, false, 'NEETCODE'),
  ('problem_lc_27', 'remove-element', 'Remove Element', 'EASY', 'Array / String', 100027, 27, false, 'NEETCODE'),
  ('problem_lc_28', 'find-the-index-of-the-first-occurrence-in-a-string', 'Find the Index of the First Occurrence in a String', 'EASY', 'Array / String', 100028, 28, false, 'NEETCODE'),
  ('problem_lc_30', 'substring-with-concatenation-of-all-words', 'Substring with Concatenation of All Words', 'HARD', 'Sliding Window', 100030, 30, false, 'NEETCODE'),
  ('problem_lc_33', 'search-in-rotated-sorted-array', 'Search in Rotated Sorted Array', 'MEDIUM', 'Binary Search', 100033, 33, false, 'NEETCODE'),
  ('problem_lc_34', 'find-first-and-last-position-of-element-in-sorted-array', 'Find First and Last Position of Element in Sorted Array', 'MEDIUM', 'Binary Search', 100034, 34, false, 'NEETCODE'),
  ('problem_lc_35', 'search-insert-position', 'Search Insert Position', 'EASY', 'Binary Search', 100035, 35, false, 'NEETCODE'),
  ('problem_lc_36', 'valid-sudoku', 'Valid Sudoku', 'MEDIUM', 'Matrix', 100036, 36, false, 'NEETCODE'),
  ('problem_lc_39', 'combination-sum', 'Combination Sum', 'MEDIUM', 'Backtracking', 100039, 39, false, 'NEETCODE'),
  ('problem_lc_42', 'trapping-rain-water', 'Trapping Rain Water', 'HARD', 'Array / String', 100042, 42, false, 'NEETCODE'),
  ('problem_lc_45', 'jump-game-ii', 'Jump Game II', 'MEDIUM', 'Array / String', 100045, 45, false, 'NEETCODE'),
  ('problem_lc_46', 'permutations', 'Permutations', 'MEDIUM', 'Backtracking', 100046, 46, false, 'NEETCODE'),
  ('problem_lc_48', 'rotate-image', 'Rotate Image', 'MEDIUM', 'Matrix', 100048, 48, false, 'NEETCODE'),
  ('problem_lc_49', 'group-anagrams', 'Group Anagrams', 'MEDIUM', 'Hashmap', 100049, 49, false, 'NEETCODE'),
  ('problem_lc_50', 'powx-n', 'Pow(x, n)', 'MEDIUM', 'Math', 100050, 50, false, 'NEETCODE'),
  ('problem_lc_52', 'n-queens-ii', 'N-Queens II', 'HARD', 'Backtracking', 100052, 52, false, 'NEETCODE'),
  ('problem_lc_53', 'maximum-subarray', 'Maximum Subarray', 'MEDIUM', 'Kadane''s Algorithm', 100053, 53, false, 'NEETCODE'),
  ('problem_lc_54', 'spiral-matrix', 'Spiral Matrix', 'MEDIUM', 'Matrix', 100054, 54, false, 'NEETCODE'),
  ('problem_lc_55', 'jump-game', 'Jump Game', 'MEDIUM', 'Array / String', 100055, 55, false, 'NEETCODE'),
  ('problem_lc_56', 'merge-intervals', 'Merge Intervals', 'MEDIUM', 'Intervals', 100056, 56, false, 'NEETCODE'),
  ('problem_lc_57', 'insert-interval', 'Insert Interval', 'MEDIUM', 'Intervals', 100057, 57, false, 'NEETCODE'),
  ('problem_lc_58', 'length-of-last-word', 'Length of Last Word', 'EASY', 'Array / String', 100058, 58, false, 'NEETCODE'),
  ('problem_lc_61', 'rotate-list', 'Rotate List', 'MEDIUM', 'Linked List', 100061, 61, false, 'NEETCODE'),
  ('problem_lc_62', 'unique-paths', 'Unique Paths', 'MEDIUM', 'Matrix', 100062, 62, false, 'NEETCODE'),
  ('problem_lc_63', 'unique-paths-ii', 'Unique Paths II', 'MEDIUM', 'Matrix', 100063, 63, false, 'NEETCODE'),
  ('problem_lc_64', 'minimum-path-sum', 'Minimum Path Sum', 'MEDIUM', 'Matrix', 100064, 64, false, 'NEETCODE'),
  ('problem_lc_66', 'plus-one', 'Plus One', 'EASY', 'Math', 100066, 66, false, 'NEETCODE'),
  ('problem_lc_67', 'add-binary', 'Add Binary', 'EASY', 'Bit Manipulation', 100067, 67, false, 'NEETCODE'),
  ('problem_lc_68', 'text-justification', 'Text Justification', 'HARD', 'Array / String', 100068, 68, false, 'NEETCODE'),
  ('problem_lc_69', 'sqrtx', 'Sqrt(x)', 'EASY', 'Math', 100069, 69, false, 'NEETCODE'),
  ('problem_lc_70', 'climbing-stairs', 'Climbing Stairs', 'EASY', 'Fibonacci style', 100070, 70, false, 'NEETCODE'),
  ('problem_lc_71', 'simplify-path', 'Simplify Path', 'MEDIUM', 'Stack', 100071, 71, false, 'NEETCODE'),
  ('problem_lc_72', 'edit-distance', 'Edit Distance', 'MEDIUM', 'On Strings', 100072, 72, false, 'NEETCODE'),
  ('problem_lc_73', 'set-matrix-zeroes', 'Set Matrix Zeroes', 'MEDIUM', 'Matrix', 100073, 73, false, 'NEETCODE'),
  ('problem_lc_74', 'search-a-2d-matrix', 'Search a 2D Matrix', 'MEDIUM', 'Binary Search', 100074, 74, false, 'NEETCODE'),
  ('problem_lc_76', 'minimum-window-substring', 'Minimum Window Substring', 'HARD', 'Sliding Window', 100076, 76, false, 'NEETCODE'),
  ('problem_lc_77', 'combinations', 'Combinations', 'MEDIUM', 'Backtracking', 100077, 77, false, 'NEETCODE'),
  ('problem_lc_79', 'word-search', 'Word Search', 'MEDIUM', 'Backtracking', 100079, 79, false, 'NEETCODE'),
  ('problem_lc_80', 'remove-duplicates-from-sorted-array-ii', 'Remove Duplicates from Sorted Array II', 'MEDIUM', 'Array / String', 100080, 80, false, 'NEETCODE'),
  ('problem_lc_82', 'remove-duplicates-from-sorted-list-ii', 'Remove Duplicates from Sorted List II', 'MEDIUM', 'Linked List', 100082, 82, false, 'NEETCODE'),
  ('problem_lc_86', 'partition-list', 'Partition List', 'MEDIUM', 'Linked List', 100086, 86, false, 'NEETCODE'),
  ('problem_lc_88', 'merge-sorted-array', 'Merge Sorted Array', 'EASY', 'Array / String', 100088, 88, false, 'NEETCODE'),
  ('problem_lc_91', 'decode-ways', 'Decode Ways', 'MEDIUM', 'General 1D', 100091, 91, false, 'NEETCODE'),
  ('problem_lc_92', 'reverse-linked-list-ii', 'Reverse Linked List II', 'MEDIUM', 'Linked List', 100092, 92, false, 'NEETCODE'),
  ('problem_lc_95', 'unique-binary-search-trees-ii', 'Unique Binary Search Trees II', 'MEDIUM', 'On Trees', 100095, 95, false, 'NEETCODE'),
  ('problem_lc_96', 'unique-binary-search-trees', 'Unique Binary Search Trees', 'MEDIUM', 'On Trees', 100096, 96, false, 'NEETCODE'),
  ('problem_lc_97', 'interleaving-string', 'Interleaving String', 'MEDIUM', 'Multidimensional DP', 100097, 97, false, 'NEETCODE'),
  ('problem_lc_98', 'validate-binary-search-tree', 'Validate Binary Search Tree', 'MEDIUM', 'Binary Search Tree', 100098, 98, false, 'NEETCODE'),
  ('problem_lc_100', 'same-tree', 'Same Tree', 'EASY', 'Binary Tree General', 100100, 100, false, 'NEETCODE'),
  ('problem_lc_101', 'symmetric-tree', 'Symmetric Tree', 'EASY', 'Binary Tree General', 100101, 101, false, 'NEETCODE'),
  ('problem_lc_102', 'binary-tree-level-order-traversal', 'Binary Tree Level Order Traversal', 'MEDIUM', 'Binary Tree BFS', 100102, 102, false, 'NEETCODE'),
  ('problem_lc_103', 'binary-tree-zigzag-level-order-traversal', 'Binary Tree Zigzag Level Order Traversal', 'MEDIUM', 'Binary Tree BFS', 100103, 103, false, 'NEETCODE'),
  ('problem_lc_104', 'maximum-depth-of-binary-tree', 'Maximum Depth of Binary Tree', 'EASY', 'Binary Tree General', 100104, 104, false, 'NEETCODE'),
  ('problem_lc_105', 'construct-binary-tree-from-preorder-and-inorder-traversal', 'Construct Binary Tree from Preorder and Inorder Traversal', 'MEDIUM', 'Binary Tree General', 100105, 105, false, 'NEETCODE'),
  ('problem_lc_106', 'construct-binary-tree-from-inorder-and-postorder-traversal', 'Construct Binary Tree from Inorder and Postorder Traversal', 'MEDIUM', 'Binary Tree General', 100106, 106, false, 'NEETCODE'),
  ('problem_lc_108', 'convert-sorted-array-to-binary-search-tree', 'Convert Sorted Array to Binary Search Tree', 'EASY', 'Divide & Conquer', 100108, 108, false, 'NEETCODE'),
  ('problem_lc_112', 'path-sum', 'Path Sum', 'EASY', 'Binary Tree General', 100112, 112, false, 'NEETCODE'),
  ('problem_lc_114', 'flatten-binary-tree-to-linked-list', 'Flatten Binary Tree to Linked List', 'MEDIUM', 'Binary Tree General', 100114, 114, false, 'NEETCODE'),
  ('problem_lc_115', 'distinct-subsequences', 'Distinct Subsequences', 'HARD', 'On Strings', 100115, 115, false, 'NEETCODE'),
  ('problem_lc_117', 'populating-next-right-pointers-in-each-node-ii', 'Populating Next Right Pointers in Each Node II', 'MEDIUM', 'Binary Tree General', 100117, 117, false, 'NEETCODE'),
  ('problem_lc_120', 'triangle', 'Triangle', 'MEDIUM', 'Matrix', 100120, 120, false, 'NEETCODE'),
  ('problem_lc_121', 'best-time-to-buy-and-sell-stock', 'Best Time to Buy and Sell Stock', 'EASY', 'Array / String', 100121, 121, false, 'NEETCODE'),
  ('problem_lc_122', 'best-time-to-buy-and-sell-stock-ii', 'Best Time to Buy and Sell Stock II', 'MEDIUM', 'Array / String', 100122, 122, false, 'NEETCODE'),
  ('problem_lc_123', 'best-time-to-buy-and-sell-stock-iii', 'Best Time to Buy and Sell Stock III', 'HARD', 'Best Time to Buy & Sell Stock / State Machine', 100123, 123, false, 'NEETCODE'),
  ('problem_lc_124', 'binary-tree-maximum-path-sum', 'Binary Tree Maximum Path Sum', 'HARD', 'On Trees', 100124, 124, false, 'NEETCODE'),
  ('problem_lc_125', 'valid-palindrome', 'Valid Palindrome', 'EASY', 'Two Pointers', 100125, 125, false, 'NEETCODE'),
  ('problem_lc_127', 'word-ladder', 'Word Ladder', 'HARD', 'Graph BFS', 100127, 127, false, 'NEETCODE'),
  ('problem_lc_128', 'longest-consecutive-sequence', 'Longest Consecutive Sequence', 'MEDIUM', 'Hashmap', 100128, 128, false, 'NEETCODE'),
  ('problem_lc_129', 'sum-root-to-leaf-numbers', 'Sum Root to Leaf Numbers', 'MEDIUM', 'Binary Tree General', 100129, 129, false, 'NEETCODE'),
  ('problem_lc_130', 'surrounded-regions', 'Surrounded Regions', 'MEDIUM', 'Graph General', 100130, 130, false, 'NEETCODE'),
  ('problem_lc_133', 'clone-graph', 'Clone Graph', 'MEDIUM', 'Graph General', 100133, 133, false, 'NEETCODE'),
  ('problem_lc_134', 'gas-station', 'Gas Station', 'MEDIUM', 'Array / String', 100134, 134, false, 'NEETCODE'),
  ('problem_lc_135', 'candy', 'Candy', 'HARD', 'Array / String', 100135, 135, false, 'NEETCODE'),
  ('problem_lc_136', 'single-number', 'Single Number', 'EASY', 'Bit Manipulation', 100136, 136, false, 'NEETCODE'),
  ('problem_lc_137', 'single-number-ii', 'Single Number II', 'MEDIUM', 'Bit Manipulation', 100137, 137, false, 'NEETCODE'),
  ('problem_lc_138', 'copy-list-with-random-pointer', 'Copy List with Random Pointer', 'MEDIUM', 'Linked List', 100138, 138, false, 'NEETCODE'),
  ('problem_lc_139', 'word-break', 'Word Break', 'MEDIUM', 'On Strings', 100139, 139, false, 'NEETCODE'),
  ('problem_lc_141', 'linked-list-cycle', 'Linked List Cycle', 'EASY', 'Linked List', 100141, 141, false, 'NEETCODE'),
  ('problem_lc_146', 'lru-cache', 'LRU Cache', 'MEDIUM', 'Linked List', 100146, 146, false, 'NEETCODE'),
  ('problem_lc_148', 'sort-list', 'Sort List', 'MEDIUM', 'Divide & Conquer', 100148, 148, false, 'NEETCODE'),
  ('problem_lc_149', 'max-points-on-a-line', 'Max Points on a Line', 'HARD', 'Math', 100149, 149, false, 'NEETCODE'),
  ('problem_lc_150', 'evaluate-reverse-polish-notation', 'Evaluate Reverse Polish Notation', 'MEDIUM', 'Stack', 100150, 150, false, 'NEETCODE'),
  ('problem_lc_151', 'reverse-words-in-a-string', 'Reverse Words in a String', 'MEDIUM', 'Array / String', 100151, 151, false, 'NEETCODE'),
  ('problem_lc_153', 'find-minimum-in-rotated-sorted-array', 'Find Minimum in Rotated Sorted Array', 'MEDIUM', 'Binary Search', 100153, 153, false, 'NEETCODE'),
  ('problem_lc_155', 'min-stack', 'Min Stack', 'MEDIUM', 'Stack', 100155, 155, false, 'NEETCODE'),
  ('problem_lc_162', 'find-peak-element', 'Find Peak Element', 'MEDIUM', 'Binary Search', 100162, 162, false, 'NEETCODE'),
  ('problem_lc_167', 'two-sum-ii-input-array-is-sorted', 'Two Sum II - Input Array Is Sorted', 'MEDIUM', 'Two Pointers', 100167, 167, false, 'NEETCODE'),
  ('problem_lc_169', 'majority-element', 'Majority Element', 'EASY', 'Array / String', 100169, 169, false, 'NEETCODE'),
  ('problem_lc_172', 'factorial-trailing-zeroes', 'Factorial Trailing Zeroes', 'MEDIUM', 'Math', 100172, 172, false, 'NEETCODE'),
  ('problem_lc_173', 'binary-search-tree-iterator', 'Binary Search Tree Iterator', 'MEDIUM', 'Binary Tree General', 100173, 173, false, 'NEETCODE'),
  ('problem_lc_176', 'second-highest-salary', 'Second Highest Salary', 'MEDIUM', 'Advanced String Functions / Regex / Clause', 100176, 176, false, 'NEETCODE'),
  ('problem_lc_180', 'consecutive-numbers', 'Consecutive Numbers', 'MEDIUM', 'Advanced Select and Joins', 100180, 180, false, 'NEETCODE'),
  ('problem_lc_185', 'department-top-three-salaries', 'Department Top Three Salaries', 'HARD', 'Subqueries', 100185, 185, false, 'NEETCODE'),
  ('problem_lc_188', 'best-time-to-buy-and-sell-stock-iv', 'Best Time to Buy and Sell Stock IV', 'HARD', 'Best Time to Buy & Sell Stock / State Machine', 100188, 188, false, 'NEETCODE'),
  ('problem_lc_189', 'rotate-array', 'Rotate Array', 'MEDIUM', 'Array / String', 100189, 189, false, 'NEETCODE'),
  ('problem_lc_190', 'reverse-bits', 'Reverse Bits', 'EASY', 'Bit Manipulation', 100190, 190, false, 'NEETCODE'),
  ('problem_lc_191', 'number-of-1-bits', 'Number of 1 Bits', 'EASY', 'Bit Manipulation', 100191, 191, false, 'NEETCODE'),
  ('problem_lc_196', 'delete-duplicate-emails', 'Delete Duplicate Emails', 'EASY', 'Advanced String Functions / Regex / Clause', 100196, 196, false, 'NEETCODE'),
  ('problem_lc_197', 'rising-temperature', 'Rising Temperature', 'EASY', 'Basic Joins', 100197, 197, false, 'NEETCODE'),
  ('problem_lc_198', 'house-robber', 'House Robber', 'MEDIUM', 'Fibonacci style', 100198, 198, false, 'NEETCODE'),
  ('problem_lc_199', 'binary-tree-right-side-view', 'Binary Tree Right Side View', 'MEDIUM', 'Binary Tree BFS', 100199, 199, false, 'NEETCODE'),
  ('problem_lc_200', 'number-of-islands', 'Number of Islands', 'MEDIUM', 'Graph General', 100200, 200, false, 'NEETCODE'),
  ('problem_lc_201', 'bitwise-and-of-numbers-range', 'Bitwise AND of Numbers Range', 'MEDIUM', 'Bit Manipulation', 100201, 201, false, 'NEETCODE'),
  ('problem_lc_202', 'happy-number', 'Happy Number', 'EASY', 'Hashmap', 100202, 202, false, 'NEETCODE'),
  ('problem_lc_205', 'isomorphic-strings', 'Isomorphic Strings', 'EASY', 'Hashmap', 100205, 205, false, 'NEETCODE'),
  ('problem_lc_207', 'course-schedule', 'Course Schedule', 'MEDIUM', 'Graph General', 100207, 207, false, 'NEETCODE'),
  ('problem_lc_208', 'implement-trie-prefix-tree', 'Implement Trie (Prefix Tree)', 'MEDIUM', 'Trie', 100208, 208, false, 'NEETCODE'),
  ('problem_lc_209', 'minimum-size-subarray-sum', 'Minimum Size Subarray Sum', 'MEDIUM', 'Sliding Window', 100209, 209, false, 'NEETCODE'),
  ('problem_lc_210', 'course-schedule-ii', 'Course Schedule II', 'MEDIUM', 'Graph General', 100210, 210, false, 'NEETCODE'),
  ('problem_lc_211', 'design-add-and-search-words-data-structure', 'Design Add and Search Words Data Structure', 'MEDIUM', 'Trie', 100211, 211, false, 'NEETCODE'),
  ('problem_lc_212', 'word-search-ii', 'Word Search II', 'HARD', 'Trie', 100212, 212, false, 'NEETCODE'),
  ('problem_lc_215', 'kth-largest-element-in-an-array', 'Kth Largest Element in an Array', 'MEDIUM', 'Heap', 100215, 215, false, 'NEETCODE'),
  ('problem_lc_219', 'contains-duplicate-ii', 'Contains Duplicate II', 'EASY', 'Hashmap', 100219, 219, false, 'NEETCODE'),
  ('problem_lc_221', 'maximal-square', 'Maximal Square', 'MEDIUM', 'Matrix', 100221, 221, false, 'NEETCODE'),
  ('problem_lc_222', 'count-complete-tree-nodes', 'Count Complete Tree Nodes', 'EASY', 'Binary Tree General', 100222, 222, false, 'NEETCODE'),
  ('problem_lc_224', 'basic-calculator', 'Basic Calculator', 'HARD', 'Stack', 100224, 224, false, 'NEETCODE'),
  ('problem_lc_226', 'invert-binary-tree', 'Invert Binary Tree', 'EASY', 'Binary Tree General', 100226, 226, false, 'NEETCODE'),
  ('problem_lc_228', 'summary-ranges', 'Summary Ranges', 'EASY', 'Intervals', 100228, 228, false, 'NEETCODE'),
  ('problem_lc_230', 'kth-smallest-element-in-a-bst', 'Kth Smallest Element in a BST', 'MEDIUM', 'Binary Search Tree', 100230, 230, false, 'NEETCODE'),
  ('problem_lc_236', 'lowest-common-ancestor-of-a-binary-tree', 'Lowest Common Ancestor of a Binary Tree', 'MEDIUM', 'Binary Tree General', 100236, 236, false, 'NEETCODE'),
  ('problem_lc_238', 'product-of-array-except-self', 'Product of Array Except Self', 'MEDIUM', 'Array / String', 100238, 238, false, 'NEETCODE'),
  ('problem_lc_242', 'valid-anagram', 'Valid Anagram', 'EASY', 'Hashmap', 100242, 242, false, 'NEETCODE'),
  ('problem_lc_274', 'h-index', 'H-Index', 'MEDIUM', 'Array / String', 100274, 274, false, 'NEETCODE'),
  ('problem_lc_279', 'perfect-squares', 'Perfect Squares', 'MEDIUM', 'Knapsack', 100279, 279, false, 'NEETCODE'),
  ('problem_lc_289', 'game-of-life', 'Game of Life', 'MEDIUM', 'Matrix', 100289, 289, false, 'NEETCODE'),
  ('problem_lc_290', 'word-pattern', 'Word Pattern', 'EASY', 'Hashmap', 100290, 290, false, 'NEETCODE'),
  ('problem_lc_295', 'find-median-from-data-stream', 'Find Median from Data Stream', 'HARD', 'Heap', 100295, 295, false, 'NEETCODE'),
  ('problem_lc_300', 'longest-increasing-subsequence', 'Longest Increasing Subsequence', 'MEDIUM', 'Longest Increasing Subsequence', 100300, 300, false, 'NEETCODE'),
  ('problem_lc_309', 'best-time-to-buy-and-sell-stock-with-cooldown', 'Best Time to Buy and Sell Stock with Cooldown', 'MEDIUM', 'Best Time to Buy & Sell Stock / State Machine', 100309, 309, false, 'NEETCODE'),
  ('problem_lc_322', 'coin-change', 'Coin Change', 'MEDIUM', 'General 1D', 100322, 322, false, 'NEETCODE'),
  ('problem_lc_337', 'house-robber-iii', 'House Robber III', 'MEDIUM', 'On Trees', 100337, 337, false, 'NEETCODE'),
  ('problem_lc_354', 'russian-doll-envelopes', 'Russian Doll Envelopes', 'HARD', 'Longest Increasing Subsequence', 100354, 354, false, 'NEETCODE'),
  ('problem_lc_373', 'find-k-pairs-with-smallest-sums', 'Find K Pairs with Smallest Sums', 'MEDIUM', 'Heap', 100373, 373, false, 'NEETCODE'),
  ('problem_lc_377', 'combination-sum-iv', 'Combination Sum IV', 'MEDIUM', 'Knapsack', 100377, 377, false, 'NEETCODE'),
  ('problem_lc_380', 'insert-delete-getrandom-o1', 'Insert Delete GetRandom O(1)', 'MEDIUM', 'Array / String', 100380, 380, false, 'NEETCODE'),
  ('problem_lc_383', 'ransom-note', 'Ransom Note', 'EASY', 'Hashmap', 100383, 383, false, 'NEETCODE'),
  ('problem_lc_392', 'is-subsequence', 'Is Subsequence', 'EASY', 'Two Pointers', 100392, 392, false, 'NEETCODE'),
  ('problem_lc_399', 'evaluate-division', 'Evaluate Division', 'MEDIUM', 'Graph General', 100399, 399, false, 'NEETCODE'),
  ('problem_lc_427', 'construct-quad-tree', 'Construct Quad Tree', 'MEDIUM', 'Divide & Conquer', 100427, 427, false, 'NEETCODE'),
  ('problem_lc_433', 'minimum-genetic-mutation', 'Minimum Genetic Mutation', 'MEDIUM', 'Graph BFS', 100433, 433, false, 'NEETCODE'),
  ('problem_lc_452', 'minimum-number-of-arrows-to-burst-balloons', 'Minimum Number of Arrows to Burst Balloons', 'MEDIUM', 'Intervals', 100452, 452, false, 'NEETCODE'),
  ('problem_lc_474', 'ones-and-zeroes', 'Ones and Zeroes', 'MEDIUM', 'Knapsack', 100474, 474, false, 'NEETCODE'),
  ('problem_lc_502', 'ipo', 'IPO', 'HARD', 'Heap', 100502, 502, false, 'NEETCODE'),
  ('problem_lc_509', 'fibonacci-number', 'Fibonacci Number', 'EASY', 'Fibonacci style', 100509, 509, false, 'NEETCODE'),
  ('problem_lc_516', 'longest-palindromic-subsequence', 'Longest Palindromic Subsequence', 'MEDIUM', 'On Strings', 100516, 516, false, 'NEETCODE'),
  ('problem_lc_518', 'coin-change-ii', 'Coin Change II', 'MEDIUM', 'Knapsack', 100518, 518, false, 'NEETCODE'),
  ('problem_lc_530', 'minimum-absolute-difference-in-bst', 'Minimum Absolute Difference in BST', 'EASY', 'Binary Search Tree', 100530, 530, false, 'NEETCODE'),
  ('problem_lc_550', 'game-play-analysis-iv', 'Game Play Analysis IV', 'MEDIUM', 'Basic Aggregate Functions', 100550, 550, false, 'NEETCODE'),
  ('problem_lc_570', 'managers-with-at-least-5-direct-reports', 'Managers with at Least 5 Direct Reports', 'MEDIUM', 'Basic Joins', 100570, 570, false, 'NEETCODE'),
  ('problem_lc_577', 'employee-bonus', 'Employee Bonus', 'EASY', 'Basic Joins', 100577, 577, false, 'NEETCODE'),
  ('problem_lc_584', 'find-customer-referee', 'Find Customer Referee', 'EASY', 'Select', 100584, 584, false, 'NEETCODE'),
  ('problem_lc_585', 'investments-in-2016', 'Investments in 2016', 'MEDIUM', 'Subqueries', 100585, 585, false, 'NEETCODE'),
  ('problem_lc_595', 'big-countries', 'Big Countries', 'EASY', 'Select', 100595, 595, false, 'NEETCODE'),
  ('problem_lc_596', 'classes-with-at-least-5-students', 'Classes With at Least 5 Students', 'EASY', 'Sorting and Grouping', 100596, 596, false, 'NEETCODE'),
  ('problem_lc_602', 'friend-requests-ii-who-has-the-most-friends', 'Friend Requests II: Who Has the Most Friends', 'MEDIUM', 'Subqueries', 100602, 602, false, 'NEETCODE'),
  ('problem_lc_610', 'triangle-judgement', 'Triangle Judgement', 'EASY', 'Advanced Select and Joins', 100610, 610, false, 'NEETCODE'),
  ('problem_lc_619', 'biggest-single-number', 'Biggest Single Number', 'EASY', 'Sorting and Grouping', 100619, 619, false, 'NEETCODE'),
  ('problem_lc_620', 'not-boring-movies', 'Not Boring Movies', 'EASY', 'Basic Aggregate Functions', 100620, 620, false, 'NEETCODE'),
  ('problem_lc_626', 'exchange-seats', 'Exchange Seats', 'MEDIUM', 'Subqueries', 100626, 626, false, 'NEETCODE'),
  ('problem_lc_637', 'average-of-levels-in-binary-tree', 'Average of Levels in Binary Tree', 'EASY', 'Binary Tree BFS', 100637, 637, false, 'NEETCODE'),
  ('problem_lc_646', 'maximum-length-of-pair-chain', 'Maximum Length of Pair Chain', 'MEDIUM', 'Longest Increasing Subsequence', 100646, 646, false, 'NEETCODE'),
  ('problem_lc_673', 'number-of-longest-increasing-subsequence', 'Number of Longest Increasing Subsequence', 'MEDIUM', 'Longest Increasing Subsequence', 100673, 673, false, 'NEETCODE'),
  ('problem_lc_712', 'minimum-ascii-delete-sum-for-two-strings', 'Minimum ASCII Delete Sum for Two Strings', 'MEDIUM', 'On Strings', 100712, 712, false, 'NEETCODE'),
  ('problem_lc_714', 'best-time-to-buy-and-sell-stock-with-transaction-fee', 'Best Time to Buy and Sell Stock with Transaction Fee', 'MEDIUM', 'Best Time to Buy & Sell Stock / State Machine', 100714, 714, false, 'NEETCODE'),
  ('problem_lc_740', 'delete-and-earn', 'Delete and Earn', 'MEDIUM', 'Fibonacci style', 100740, 740, false, 'NEETCODE'),
  ('problem_lc_746', 'min-cost-climbing-stairs', 'Min Cost Climbing Stairs', 'EASY', 'Fibonacci style', 100746, 746, false, 'NEETCODE'),
  ('problem_lc_790', 'domino-and-tromino-tiling', 'Domino and Tromino Tiling', 'MEDIUM', 'General 1D', 100790, 790, false, 'NEETCODE'),
  ('problem_lc_909', 'snakes-and-ladders', 'Snakes and Ladders', 'MEDIUM', 'Graph BFS', 100909, 909, false, 'NEETCODE'),
  ('problem_lc_918', 'maximum-sum-circular-subarray', 'Maximum Sum Circular Subarray', 'MEDIUM', 'Kadane''s Algorithm', 100918, 918, false, 'NEETCODE'),
  ('problem_lc_931', 'minimum-falling-path-sum', 'Minimum Falling Path Sum', 'MEDIUM', 'Matrix', 100931, 931, false, 'NEETCODE'),
  ('problem_lc_983', 'minimum-cost-for-tickets', 'Minimum Cost For Tickets', 'MEDIUM', 'General 1D', 100983, 983, false, 'NEETCODE'),
  ('problem_lc_1027', 'longest-arithmetic-subsequence', 'Longest Arithmetic Subsequence', 'MEDIUM', 'Longest Increasing Subsequence', 101027, 1027, false, 'NEETCODE'),
  ('problem_lc_1035', 'uncrossed-lines', 'Uncrossed Lines', 'MEDIUM', 'Longest Common Subsequence', 101035, 1035, false, 'NEETCODE'),
  ('problem_lc_1045', 'customers-who-bought-all-products', 'Customers Who Bought All Products', 'MEDIUM', 'Sorting and Grouping', 101045, 1045, false, 'NEETCODE'),
  ('problem_lc_1068', 'product-sales-analysis-i', 'Product Sales Analysis I', 'EASY', 'Basic Joins', 101068, 1068, false, 'NEETCODE'),
  ('problem_lc_1070', 'product-sales-analysis-iii', 'Product Sales Analysis III', 'MEDIUM', 'Sorting and Grouping', 101070, 1070, false, 'NEETCODE'),
  ('problem_lc_1075', 'project-employees-i', 'Project Employees I', 'EASY', 'Basic Aggregate Functions', 101075, 1075, false, 'NEETCODE'),
  ('problem_lc_1137', 'n-th-tribonacci-number', 'N-th Tribonacci Number', 'EASY', 'Fibonacci style', 101137, 1137, false, 'NEETCODE'),
  ('problem_lc_1141', 'user-activity-for-the-past-30-days-i', 'User Activity for the Past 30 Days I', 'EASY', 'Sorting and Grouping', 101141, 1141, false, 'NEETCODE'),
  ('problem_lc_1143', 'longest-common-subsequence', 'Longest Common Subsequence', 'MEDIUM', 'Longest Common Subsequence', 101143, 1143, false, 'NEETCODE'),
  ('problem_lc_1148', 'article-views-i', 'Article Views I', 'EASY', 'Select', 101148, 1148, false, 'NEETCODE'),
  ('problem_lc_1164', 'product-price-at-a-given-date', 'Product Price at a Given Date', 'MEDIUM', 'Advanced Select and Joins', 101164, 1164, false, 'NEETCODE'),
  ('problem_lc_1174', 'immediate-food-delivery-ii', 'Immediate Food Delivery II', 'MEDIUM', 'Basic Aggregate Functions', 101174, 1174, false, 'NEETCODE'),
  ('problem_lc_1193', 'monthly-transactions-i', 'Monthly Transactions I', 'MEDIUM', 'Basic Aggregate Functions', 101193, 1193, false, 'NEETCODE'),
  ('problem_lc_1204', 'last-person-to-fit-in-the-bus', 'Last Person to Fit in the Bus', 'MEDIUM', 'Advanced Select and Joins', 101204, 1204, false, 'NEETCODE'),
  ('problem_lc_1211', 'queries-quality-and-percentage', 'Queries Quality and Percentage', 'EASY', 'Basic Aggregate Functions', 101211, 1211, false, 'NEETCODE'),
  ('problem_lc_1218', 'longest-arithmetic-subsequence-of-given-difference', 'Longest Arithmetic Subsequence of Given Difference', 'MEDIUM', 'Longest Increasing Subsequence', 101218, 1218, false, 'NEETCODE'),
  ('problem_lc_1251', 'average-selling-price', 'Average Selling Price', 'EASY', 'Basic Aggregate Functions', 101251, 1251, false, 'NEETCODE'),
  ('problem_lc_1280', 'students-and-examinations', 'Students and Examinations', 'EASY', 'Basic Joins', 101280, 1280, false, 'NEETCODE'),
  ('problem_lc_1312', 'minimum-insertion-steps-to-make-a-string-palindrome', 'Minimum Insertion Steps to Make a String Palindrome', 'HARD', 'Longest Common Subsequence', 101312, 1312, false, 'NEETCODE'),
  ('problem_lc_1321', 'restaurant-growth', 'Restaurant Growth', 'MEDIUM', 'Subqueries', 101321, 1321, false, 'NEETCODE'),
  ('problem_lc_1327', 'list-the-products-ordered-in-a-period', 'List the Products Ordered in a Period', 'EASY', 'Advanced String Functions / Regex / Clause', 101327, 1327, false, 'NEETCODE'),
  ('problem_lc_1341', 'movie-rating', 'Movie Rating', 'MEDIUM', 'Subqueries', 101341, 1341, false, 'NEETCODE'),
  ('problem_lc_1378', 'replace-employee-id-with-the-unique-identifier', 'Replace Employee ID With The Unique Identifier', 'EASY', 'Basic Joins', 101378, 1378, false, 'NEETCODE'),
  ('problem_lc_1484', 'group-sold-products-by-the-date', 'Group Sold Products By The Date', 'EASY', 'Advanced String Functions / Regex / Clause', 101484, 1484, false, 'NEETCODE'),
  ('problem_lc_1517', 'find-users-with-valid-e-mails', 'Find Users With Valid E-Mails', 'EASY', 'Advanced String Functions / Regex / Clause', 101517, 1517, false, 'NEETCODE'),
  ('problem_lc_1527', 'patients-with-a-condition', 'Patients With a Condition', 'EASY', 'Advanced String Functions / Regex / Clause', 101527, 1527, false, 'NEETCODE'),
  ('problem_lc_1581', 'customer-who-visited-but-did-not-make-any-transactions', 'Customer Who Visited but Did Not Make Any Transactions', 'EASY', 'Basic Joins', 101581, 1581, false, 'NEETCODE'),
  ('problem_lc_1633', 'percentage-of-users-attended-a-contest', 'Percentage of Users Attended a Contest', 'EASY', 'Basic Aggregate Functions', 101633, 1633, false, 'NEETCODE'),
  ('problem_lc_1661', 'average-time-of-process-per-machine', 'Average Time of Process per Machine', 'EASY', 'Basic Joins', 101661, 1661, false, 'NEETCODE'),
  ('problem_lc_1667', 'fix-names-in-a-table', 'Fix Names in a Table', 'EASY', 'Advanced String Functions / Regex / Clause', 101667, 1667, false, 'NEETCODE'),
  ('problem_lc_1683', 'invalid-tweets', 'Invalid Tweets', 'EASY', 'Select', 101683, 1683, false, 'NEETCODE'),
  ('problem_lc_1729', 'find-followers-count', 'Find Followers Count', 'EASY', 'Sorting and Grouping', 101729, 1729, false, 'NEETCODE'),
  ('problem_lc_1731', 'the-number-of-employees-which-report-to-each-employee', 'The Number of Employees Which Report to Each Employee', 'EASY', 'Advanced Select and Joins', 101731, 1731, false, 'NEETCODE'),
  ('problem_lc_1757', 'recyclable-and-low-fat-products', 'Recyclable and Low Fat Products', 'EASY', 'Select', 101757, 1757, false, 'NEETCODE'),
  ('problem_lc_1789', 'primary-department-for-each-employee', 'Primary Department for Each Employee', 'EASY', 'Advanced Select and Joins', 101789, 1789, false, 'NEETCODE'),
  ('problem_lc_1907', 'count-salary-categories', 'Count Salary Categories', 'MEDIUM', 'Advanced Select and Joins', 101907, 1907, false, 'NEETCODE'),
  ('problem_lc_1934', 'confirmation-rate', 'Confirmation Rate', 'MEDIUM', 'Basic Joins', 101934, 1934, false, 'NEETCODE'),
  ('problem_lc_1964', 'find-the-longest-valid-obstacle-course-at-each-position', 'Find the Longest Valid Obstacle Course at Each Position', 'HARD', 'Longest Increasing Subsequence', 101964, 1964, false, 'NEETCODE'),
  ('problem_lc_1978', 'employees-whose-manager-left-the-company', 'Employees Whose Manager Left the Company', 'EASY', 'Subqueries', 101978, 1978, false, 'NEETCODE'),
  ('problem_lc_2140', 'solving-questions-with-brainpower', 'Solving Questions With Brainpower', 'MEDIUM', 'General 1D', 102140, 2140, false, 'NEETCODE'),
  ('problem_lc_2356', 'number-of-unique-subjects-taught-by-each-teacher', 'Number of Unique Subjects Taught by Each Teacher', 'EASY', 'Sorting and Grouping', 102356, 2356, false, 'NEETCODE'),
  ('problem_lc_2466', 'count-ways-to-build-good-strings', 'Count Ways To Build Good Strings', 'MEDIUM', 'General 1D', 102466, 2466, false, 'NEETCODE'),
  ('problem_lc_2619', 'array-prototype-last', 'Array Prototype Last', 'EASY', 'JSON', 102619, 2619, false, 'NEETCODE'),
  ('problem_lc_2620', 'counter', 'Counter', 'EASY', 'Closures', 102620, 2620, false, 'NEETCODE'),
  ('problem_lc_2621', 'sleep', 'Sleep', 'EASY', 'Promises and Time', 102621, 2621, false, 'NEETCODE'),
  ('problem_lc_2622', 'cache-with-time-limit', 'Cache With Time Limit', 'MEDIUM', 'Promises and Time', 102622, 2622, false, 'NEETCODE'),
  ('problem_lc_2623', 'memoize', 'Memoize', 'MEDIUM', 'Function Transformations', 102623, 2623, false, 'NEETCODE'),
  ('problem_lc_2625', 'flatten-deeply-nested-array', 'Flatten Deeply Nested Array', 'MEDIUM', 'JSON', 102625, 2625, false, 'NEETCODE'),
  ('problem_lc_2626', 'array-reduce-transformation', 'Array Reduce Transformation', 'EASY', 'Basic Array Transformations', 102626, 2626, false, 'NEETCODE'),
  ('problem_lc_2627', 'debounce', 'Debounce', 'MEDIUM', 'Promises and Time', 102627, 2627, false, 'NEETCODE'),
  ('problem_lc_2629', 'function-composition', 'Function Composition', 'EASY', 'Function Transformations', 102629, 2629, false, 'NEETCODE'),
  ('problem_lc_2631', 'group-by', 'Group By', 'MEDIUM', 'JSON', 102631, 2631, false, 'NEETCODE'),
  ('problem_lc_2634', 'filter-elements-from-array', 'Filter Elements from Array', 'EASY', 'Basic Array Transformations', 102634, 2634, false, 'NEETCODE'),
  ('problem_lc_2635', 'apply-transform-over-each-element-in-array', 'Apply Transform Over Each Element in Array', 'EASY', 'Basic Array Transformations', 102635, 2635, false, 'NEETCODE'),
  ('problem_lc_2637', 'promise-time-limit', 'Promise Time Limit', 'MEDIUM', 'Promises and Time', 102637, 2637, false, 'NEETCODE'),
  ('problem_lc_2665', 'counter-ii', 'Counter II', 'EASY', 'Closures', 102665, 2665, false, 'NEETCODE'),
  ('problem_lc_2666', 'allow-one-function-call', 'Allow One Function Call', 'EASY', 'Function Transformations', 102666, 2666, false, 'NEETCODE'),
  ('problem_lc_2667', 'create-hello-world-function', 'Create Hello World Function', 'EASY', 'Closures', 102667, 2667, false, 'NEETCODE'),
  ('problem_lc_2677', 'chunk-array', 'Chunk Array', 'EASY', 'JSON', 102677, 2677, false, 'NEETCODE'),
  ('problem_lc_2694', 'event-emitter', 'Event Emitter', 'MEDIUM', 'Classes', 102694, 2694, false, 'NEETCODE'),
  ('problem_lc_2695', 'array-wrapper', 'Array Wrapper', 'EASY', 'Classes', 102695, 2695, false, 'NEETCODE'),
  ('problem_lc_2703', 'return-length-of-arguments-passed', 'Return Length of Arguments Passed', 'EASY', 'Function Transformations', 102703, 2703, false, 'NEETCODE'),
  ('problem_lc_2704', 'to-be-or-not-to-be', 'To Be Or Not To Be', 'EASY', 'Closures', 102704, 2704, false, 'NEETCODE'),
  ('problem_lc_2705', 'compact-object', 'Compact Object', 'MEDIUM', 'JSON', 102705, 2705, false, 'NEETCODE'),
  ('problem_lc_2715', 'timeout-cancellation', 'Timeout Cancellation', 'EASY', 'Promises and Time', 102715, 2715, false, 'NEETCODE'),
  ('problem_lc_2721', 'execute-asynchronous-functions-in-parallel', 'Execute Asynchronous Functions in Parallel', 'MEDIUM', 'Promises and Time', 102721, 2721, false, 'NEETCODE'),
  ('problem_lc_2722', 'join-two-arrays-by-id', 'Join Two Arrays by ID', 'MEDIUM', 'JSON', 102722, 2722, false, 'NEETCODE'),
  ('problem_lc_2723', 'add-two-promises', 'Add Two Promises', 'EASY', 'Promises and Time', 102723, 2723, false, 'NEETCODE'),
  ('problem_lc_2724', 'sort-by', 'Sort By', 'EASY', 'JSON', 102724, 2724, false, 'NEETCODE'),
  ('problem_lc_2725', 'interval-cancellation', 'Interval Cancellation', 'EASY', 'Promises and Time', 102725, 2725, false, 'NEETCODE'),
  ('problem_lc_2726', 'calculator-with-method-chaining', 'Calculator with Method Chaining', 'EASY', 'Classes', 102726, 2726, false, 'NEETCODE'),
  ('problem_lc_2727', 'is-object-empty', 'Is Object Empty', 'EASY', 'JSON', 102727, 2727, false, 'NEETCODE')
ON CONFLICT ("slug") DO NOTHING;

DELETE FROM "RoadmapProblem"
WHERE "roadmapId" IN ('roadmap_top_interview_150', 'roadmap_top_sql_50', 'roadmap_dynamic_programming', 'roadmap_js_30');

INSERT INTO "RoadmapProblem" ("roadmapId", "problemId", "position", "topic", "updatedAt")
SELECT 'roadmap_top_interview_150', p.id, data.position, data.topic, CURRENT_TIMESTAMP
FROM (VALUES
    (1, 'merge-sorted-array', 'Array / String'),
    (2, 'remove-element', 'Array / String'),
    (3, 'remove-duplicates-from-sorted-array', 'Array / String'),
    (4, 'remove-duplicates-from-sorted-array-ii', 'Array / String'),
    (5, 'majority-element', 'Array / String'),
    (6, 'rotate-array', 'Array / String'),
    (7, 'best-time-to-buy-and-sell-stock', 'Array / String'),
    (8, 'best-time-to-buy-and-sell-stock-ii', 'Array / String'),
    (9, 'jump-game', 'Array / String'),
    (10, 'jump-game-ii', 'Array / String'),
    (11, 'h-index', 'Array / String'),
    (12, 'insert-delete-getrandom-o1', 'Array / String'),
    (13, 'product-of-array-except-self', 'Array / String'),
    (14, 'gas-station', 'Array / String'),
    (15, 'candy', 'Array / String'),
    (16, 'trapping-rain-water', 'Array / String'),
    (17, 'roman-to-integer', 'Array / String'),
    (18, 'integer-to-roman', 'Array / String'),
    (19, 'length-of-last-word', 'Array / String'),
    (20, 'longest-common-prefix', 'Array / String'),
    (21, 'reverse-words-in-a-string', 'Array / String'),
    (22, 'zigzag-conversion', 'Array / String'),
    (23, 'find-the-index-of-the-first-occurrence-in-a-string', 'Array / String'),
    (24, 'text-justification', 'Array / String'),
    (25, 'valid-palindrome', 'Two Pointers'),
    (26, 'is-subsequence', 'Two Pointers'),
    (27, 'two-sum-ii-input-array-is-sorted', 'Two Pointers'),
    (28, 'container-with-most-water', 'Two Pointers'),
    (29, '3sum', 'Two Pointers'),
    (30, 'minimum-size-subarray-sum', 'Sliding Window'),
    (31, 'longest-substring-without-repeating-characters', 'Sliding Window'),
    (32, 'substring-with-concatenation-of-all-words', 'Sliding Window'),
    (33, 'minimum-window-substring', 'Sliding Window'),
    (34, 'valid-sudoku', 'Matrix'),
    (35, 'spiral-matrix', 'Matrix'),
    (36, 'rotate-image', 'Matrix'),
    (37, 'set-matrix-zeroes', 'Matrix'),
    (38, 'game-of-life', 'Matrix'),
    (39, 'ransom-note', 'Hashmap'),
    (40, 'isomorphic-strings', 'Hashmap'),
    (41, 'word-pattern', 'Hashmap'),
    (42, 'valid-anagram', 'Hashmap'),
    (43, 'group-anagrams', 'Hashmap'),
    (44, 'two-sum', 'Hashmap'),
    (45, 'happy-number', 'Hashmap'),
    (46, 'contains-duplicate-ii', 'Hashmap'),
    (47, 'longest-consecutive-sequence', 'Hashmap'),
    (48, 'summary-ranges', 'Intervals'),
    (49, 'merge-intervals', 'Intervals'),
    (50, 'insert-interval', 'Intervals'),
    (51, 'minimum-number-of-arrows-to-burst-balloons', 'Intervals'),
    (52, 'valid-parentheses', 'Stack'),
    (53, 'simplify-path', 'Stack'),
    (54, 'min-stack', 'Stack'),
    (55, 'evaluate-reverse-polish-notation', 'Stack'),
    (56, 'basic-calculator', 'Stack'),
    (57, 'linked-list-cycle', 'Linked List'),
    (58, 'add-two-numbers', 'Linked List'),
    (59, 'merge-two-sorted-lists', 'Linked List'),
    (60, 'copy-list-with-random-pointer', 'Linked List'),
    (61, 'reverse-linked-list-ii', 'Linked List'),
    (62, 'reverse-nodes-in-k-group', 'Linked List'),
    (63, 'remove-nth-node-from-end-of-list', 'Linked List'),
    (64, 'remove-duplicates-from-sorted-list-ii', 'Linked List'),
    (65, 'rotate-list', 'Linked List'),
    (66, 'partition-list', 'Linked List'),
    (67, 'lru-cache', 'Linked List'),
    (68, 'maximum-depth-of-binary-tree', 'Binary Tree General'),
    (69, 'same-tree', 'Binary Tree General'),
    (70, 'invert-binary-tree', 'Binary Tree General'),
    (71, 'symmetric-tree', 'Binary Tree General'),
    (72, 'construct-binary-tree-from-preorder-and-inorder-traversal', 'Binary Tree General'),
    (73, 'construct-binary-tree-from-inorder-and-postorder-traversal', 'Binary Tree General'),
    (74, 'populating-next-right-pointers-in-each-node-ii', 'Binary Tree General'),
    (75, 'flatten-binary-tree-to-linked-list', 'Binary Tree General'),
    (76, 'path-sum', 'Binary Tree General'),
    (77, 'sum-root-to-leaf-numbers', 'Binary Tree General'),
    (78, 'binary-tree-maximum-path-sum', 'Binary Tree General'),
    (79, 'binary-search-tree-iterator', 'Binary Tree General'),
    (80, 'count-complete-tree-nodes', 'Binary Tree General'),
    (81, 'lowest-common-ancestor-of-a-binary-tree', 'Binary Tree General'),
    (82, 'binary-tree-right-side-view', 'Binary Tree BFS'),
    (83, 'average-of-levels-in-binary-tree', 'Binary Tree BFS'),
    (84, 'binary-tree-level-order-traversal', 'Binary Tree BFS'),
    (85, 'binary-tree-zigzag-level-order-traversal', 'Binary Tree BFS'),
    (86, 'minimum-absolute-difference-in-bst', 'Binary Search Tree'),
    (87, 'kth-smallest-element-in-a-bst', 'Binary Search Tree'),
    (88, 'validate-binary-search-tree', 'Binary Search Tree'),
    (89, 'number-of-islands', 'Graph General'),
    (90, 'surrounded-regions', 'Graph General'),
    (91, 'clone-graph', 'Graph General'),
    (92, 'evaluate-division', 'Graph General'),
    (93, 'course-schedule', 'Graph General'),
    (94, 'course-schedule-ii', 'Graph General'),
    (95, 'snakes-and-ladders', 'Graph BFS'),
    (96, 'minimum-genetic-mutation', 'Graph BFS'),
    (97, 'word-ladder', 'Graph BFS'),
    (98, 'implement-trie-prefix-tree', 'Trie'),
    (99, 'design-add-and-search-words-data-structure', 'Trie'),
    (100, 'word-search-ii', 'Trie'),
    (101, 'letter-combinations-of-a-phone-number', 'Backtracking'),
    (102, 'combinations', 'Backtracking'),
    (103, 'permutations', 'Backtracking'),
    (104, 'combination-sum', 'Backtracking'),
    (105, 'n-queens-ii', 'Backtracking'),
    (106, 'generate-parentheses', 'Backtracking'),
    (107, 'word-search', 'Backtracking'),
    (108, 'convert-sorted-array-to-binary-search-tree', 'Divide & Conquer'),
    (109, 'sort-list', 'Divide & Conquer'),
    (110, 'construct-quad-tree', 'Divide & Conquer'),
    (111, 'merge-k-sorted-lists', 'Divide & Conquer'),
    (112, 'maximum-subarray', 'Kadane''s Algorithm'),
    (113, 'maximum-sum-circular-subarray', 'Kadane''s Algorithm'),
    (114, 'search-insert-position', 'Binary Search'),
    (115, 'search-a-2d-matrix', 'Binary Search'),
    (116, 'find-peak-element', 'Binary Search'),
    (117, 'search-in-rotated-sorted-array', 'Binary Search'),
    (118, 'find-first-and-last-position-of-element-in-sorted-array', 'Binary Search'),
    (119, 'find-minimum-in-rotated-sorted-array', 'Binary Search'),
    (120, 'median-of-two-sorted-arrays', 'Binary Search'),
    (121, 'kth-largest-element-in-an-array', 'Heap'),
    (122, 'ipo', 'Heap'),
    (123, 'find-k-pairs-with-smallest-sums', 'Heap'),
    (124, 'find-median-from-data-stream', 'Heap'),
    (125, 'add-binary', 'Bit Manipulation'),
    (126, 'reverse-bits', 'Bit Manipulation'),
    (127, 'number-of-1-bits', 'Bit Manipulation'),
    (128, 'single-number', 'Bit Manipulation'),
    (129, 'single-number-ii', 'Bit Manipulation'),
    (130, 'bitwise-and-of-numbers-range', 'Bit Manipulation'),
    (131, 'palindrome-number', 'Math'),
    (132, 'plus-one', 'Math'),
    (133, 'factorial-trailing-zeroes', 'Math'),
    (134, 'sqrtx', 'Math'),
    (135, 'powx-n', 'Math'),
    (136, 'max-points-on-a-line', 'Math'),
    (137, 'climbing-stairs', '1D DP'),
    (138, 'house-robber', '1D DP'),
    (139, 'word-break', '1D DP'),
    (140, 'coin-change', '1D DP'),
    (141, 'longest-increasing-subsequence', '1D DP'),
    (142, 'triangle', 'Multidimensional DP'),
    (143, 'minimum-path-sum', 'Multidimensional DP'),
    (144, 'unique-paths-ii', 'Multidimensional DP'),
    (145, 'longest-palindromic-substring', 'Multidimensional DP'),
    (146, 'interleaving-string', 'Multidimensional DP'),
    (147, 'edit-distance', 'Multidimensional DP'),
    (148, 'best-time-to-buy-and-sell-stock-iii', 'Multidimensional DP'),
    (149, 'best-time-to-buy-and-sell-stock-iv', 'Multidimensional DP'),
    (150, 'maximal-square', 'Multidimensional DP')
) AS data(position, slug, topic)
JOIN "Problem" p ON p.slug = data.slug;

INSERT INTO "RoadmapProblem" ("roadmapId", "problemId", "position", "topic", "updatedAt")
SELECT 'roadmap_top_sql_50', p.id, data.position, data.topic, CURRENT_TIMESTAMP
FROM (VALUES
    (1, 'recyclable-and-low-fat-products', 'Select'),
    (2, 'find-customer-referee', 'Select'),
    (3, 'big-countries', 'Select'),
    (4, 'article-views-i', 'Select'),
    (5, 'invalid-tweets', 'Select'),
    (6, 'replace-employee-id-with-the-unique-identifier', 'Basic Joins'),
    (7, 'product-sales-analysis-i', 'Basic Joins'),
    (8, 'customer-who-visited-but-did-not-make-any-transactions', 'Basic Joins'),
    (9, 'rising-temperature', 'Basic Joins'),
    (10, 'average-time-of-process-per-machine', 'Basic Joins'),
    (11, 'employee-bonus', 'Basic Joins'),
    (12, 'students-and-examinations', 'Basic Joins'),
    (13, 'managers-with-at-least-5-direct-reports', 'Basic Joins'),
    (14, 'confirmation-rate', 'Basic Joins'),
    (15, 'not-boring-movies', 'Basic Aggregate Functions'),
    (16, 'average-selling-price', 'Basic Aggregate Functions'),
    (17, 'project-employees-i', 'Basic Aggregate Functions'),
    (18, 'percentage-of-users-attended-a-contest', 'Basic Aggregate Functions'),
    (19, 'queries-quality-and-percentage', 'Basic Aggregate Functions'),
    (20, 'monthly-transactions-i', 'Basic Aggregate Functions'),
    (21, 'immediate-food-delivery-ii', 'Basic Aggregate Functions'),
    (22, 'game-play-analysis-iv', 'Basic Aggregate Functions'),
    (23, 'number-of-unique-subjects-taught-by-each-teacher', 'Sorting and Grouping'),
    (24, 'user-activity-for-the-past-30-days-i', 'Sorting and Grouping'),
    (25, 'product-sales-analysis-iii', 'Sorting and Grouping'),
    (26, 'classes-with-at-least-5-students', 'Sorting and Grouping'),
    (27, 'find-followers-count', 'Sorting and Grouping'),
    (28, 'biggest-single-number', 'Sorting and Grouping'),
    (29, 'customers-who-bought-all-products', 'Sorting and Grouping'),
    (30, 'the-number-of-employees-which-report-to-each-employee', 'Advanced Select and Joins'),
    (31, 'primary-department-for-each-employee', 'Advanced Select and Joins'),
    (32, 'triangle-judgement', 'Advanced Select and Joins'),
    (33, 'consecutive-numbers', 'Advanced Select and Joins'),
    (34, 'product-price-at-a-given-date', 'Advanced Select and Joins'),
    (35, 'last-person-to-fit-in-the-bus', 'Advanced Select and Joins'),
    (36, 'count-salary-categories', 'Advanced Select and Joins'),
    (37, 'employees-whose-manager-left-the-company', 'Subqueries'),
    (38, 'exchange-seats', 'Subqueries'),
    (39, 'movie-rating', 'Subqueries'),
    (40, 'restaurant-growth', 'Subqueries'),
    (41, 'friend-requests-ii-who-has-the-most-friends', 'Subqueries'),
    (42, 'investments-in-2016', 'Subqueries'),
    (43, 'department-top-three-salaries', 'Subqueries'),
    (44, 'fix-names-in-a-table', 'Advanced String Functions / Regex / Clause'),
    (45, 'patients-with-a-condition', 'Advanced String Functions / Regex / Clause'),
    (46, 'delete-duplicate-emails', 'Advanced String Functions / Regex / Clause'),
    (47, 'second-highest-salary', 'Advanced String Functions / Regex / Clause'),
    (48, 'group-sold-products-by-the-date', 'Advanced String Functions / Regex / Clause'),
    (49, 'list-the-products-ordered-in-a-period', 'Advanced String Functions / Regex / Clause'),
    (50, 'find-users-with-valid-e-mails', 'Advanced String Functions / Regex / Clause')
) AS data(position, slug, topic)
JOIN "Problem" p ON p.slug = data.slug;

INSERT INTO "RoadmapProblem" ("roadmapId", "problemId", "position", "topic", "updatedAt")
SELECT 'roadmap_dynamic_programming', p.id, data.position, data.topic, CURRENT_TIMESTAMP
FROM (VALUES
    (1, 'climbing-stairs', 'Fibonacci style'),
    (2, 'fibonacci-number', 'Fibonacci style'),
    (3, 'n-th-tribonacci-number', 'Fibonacci style'),
    (4, 'min-cost-climbing-stairs', 'Fibonacci style'),
    (5, 'house-robber', 'Fibonacci style'),
    (6, 'delete-and-earn', 'Fibonacci style'),
    (7, 'unique-paths', 'Matrix'),
    (8, 'minimum-path-sum', 'Matrix'),
    (9, 'unique-paths-ii', 'Matrix'),
    (10, 'triangle', 'Matrix'),
    (11, 'minimum-falling-path-sum', 'Matrix'),
    (12, 'maximal-square', 'Matrix'),
    (13, 'longest-palindromic-substring', 'On Strings'),
    (14, 'word-break', 'On Strings'),
    (15, 'longest-palindromic-subsequence', 'On Strings'),
    (16, 'edit-distance', 'On Strings'),
    (17, 'minimum-ascii-delete-sum-for-two-strings', 'On Strings'),
    (18, 'distinct-subsequences', 'On Strings'),
    (19, 'longest-increasing-subsequence', 'Longest Increasing Subsequence'),
    (20, 'number-of-longest-increasing-subsequence', 'Longest Increasing Subsequence'),
    (21, 'maximum-length-of-pair-chain', 'Longest Increasing Subsequence'),
    (22, 'longest-arithmetic-subsequence-of-given-difference', 'Longest Increasing Subsequence'),
    (23, 'longest-arithmetic-subsequence', 'Longest Increasing Subsequence'),
    (24, 'russian-doll-envelopes', 'Longest Increasing Subsequence'),
    (25, 'find-the-longest-valid-obstacle-course-at-each-position', 'Longest Increasing Subsequence'),
    (26, 'longest-common-subsequence', 'Longest Common Subsequence'),
    (27, 'uncrossed-lines', 'Longest Common Subsequence'),
    (28, 'minimum-insertion-steps-to-make-a-string-palindrome', 'Longest Common Subsequence'),
    (29, 'best-time-to-buy-and-sell-stock-with-cooldown', 'Best Time to Buy & Sell Stock / State Machine'),
    (30, 'best-time-to-buy-and-sell-stock-with-transaction-fee', 'Best Time to Buy & Sell Stock / State Machine'),
    (31, 'best-time-to-buy-and-sell-stock-iii', 'Best Time to Buy & Sell Stock / State Machine'),
    (32, 'best-time-to-buy-and-sell-stock-iv', 'Best Time to Buy & Sell Stock / State Machine'),
    (33, 'unique-binary-search-trees', 'On Trees'),
    (34, 'unique-binary-search-trees-ii', 'On Trees'),
    (35, 'house-robber-iii', 'On Trees'),
    (36, 'binary-tree-maximum-path-sum', 'On Trees'),
    (37, 'perfect-squares', 'Knapsack'),
    (38, 'coin-change-ii', 'Knapsack'),
    (39, 'combination-sum-iv', 'Knapsack'),
    (40, 'ones-and-zeroes', 'Knapsack'),
    (41, 'solving-questions-with-brainpower', 'General 1D'),
    (42, 'coin-change', 'General 1D'),
    (43, 'count-ways-to-build-good-strings', 'General 1D'),
    (44, 'decode-ways', 'General 1D'),
    (45, 'minimum-cost-for-tickets', 'General 1D'),
    (46, 'domino-and-tromino-tiling', 'General 1D')
) AS data(position, slug, topic)
JOIN "Problem" p ON p.slug = data.slug;

INSERT INTO "RoadmapProblem" ("roadmapId", "problemId", "position", "topic", "updatedAt")
SELECT 'roadmap_js_30', p.id, data.position, data.topic, CURRENT_TIMESTAMP
FROM (VALUES
    (1, 'create-hello-world-function', 'Closures'),
    (2, 'counter', 'Closures'),
    (3, 'to-be-or-not-to-be', 'Closures'),
    (4, 'counter-ii', 'Closures'),
    (5, 'apply-transform-over-each-element-in-array', 'Basic Array Transformations'),
    (6, 'filter-elements-from-array', 'Basic Array Transformations'),
    (7, 'array-reduce-transformation', 'Basic Array Transformations'),
    (8, 'function-composition', 'Function Transformations'),
    (9, 'return-length-of-arguments-passed', 'Function Transformations'),
    (10, 'allow-one-function-call', 'Function Transformations'),
    (11, 'memoize', 'Function Transformations'),
    (12, 'add-two-promises', 'Promises and Time'),
    (13, 'sleep', 'Promises and Time'),
    (14, 'timeout-cancellation', 'Promises and Time'),
    (15, 'interval-cancellation', 'Promises and Time'),
    (16, 'promise-time-limit', 'Promises and Time'),
    (17, 'cache-with-time-limit', 'Promises and Time'),
    (18, 'debounce', 'Promises and Time'),
    (19, 'execute-asynchronous-functions-in-parallel', 'Promises and Time'),
    (20, 'is-object-empty', 'JSON'),
    (21, 'chunk-array', 'JSON'),
    (22, 'array-prototype-last', 'JSON'),
    (23, 'group-by', 'JSON'),
    (24, 'sort-by', 'JSON'),
    (25, 'join-two-arrays-by-id', 'JSON'),
    (26, 'flatten-deeply-nested-array', 'JSON'),
    (27, 'compact-object', 'JSON'),
    (28, 'event-emitter', 'Classes'),
    (29, 'array-wrapper', 'Classes'),
    (30, 'calculator-with-method-chaining', 'Classes')
) AS data(position, slug, topic)
JOIN "Problem" p ON p.slug = data.slug;
