export type Topic =
  | 'arrays-hashing'
  | 'two-pointers'
  | 'sliding-window'
  | 'stack'
  | 'binary-search'
  | 'linkedlist'
  | 'tree'
  | 'priority-queue'
  | 'backtracking'
  | 'tries'
  | 'graphs'
  | '1d-dp'
  | '2d-dp'

export type Difficulty = 'easy' | 'medium' | 'hard'
