/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSplatRouteImport } from './routes/api.$'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/_onboarding'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/_app'
import { Route as AuthenticatedOnboardingOnboardingRouteImport } from './routes/_authenticated/_onboarding/onboarding'
import { Route as AuthenticatedAppProblemsRouteImport } from './routes/_authenticated/_app/problems'
import { Route as AuthenticatedAppLeaderboardRouteImport } from './routes/_authenticated/_app/leaderboard'
import { Route as AuthenticatedAppGroupsRouteImport } from './routes/_authenticated/_app/groups'
import { Route as AuthenticatedAppDashboardRouteImport } from './routes/_authenticated/_app/dashboard'
import { Route as AuthenticatedAppSettingsBillingRouteImport } from './routes/_authenticated/_app/settings_/billing'
import { Route as AuthenticatedAppGroupsGroupIdRouteImport } from './routes/_authenticated/_app/groups_/$groupId'
import { Route as AuthenticatedAppGroupsGroupIdIndexRouteImport } from './routes/_authenticated/_app/groups_/$groupId/index'
import { Route as AuthenticatedAppGroupsJoinInviteCodeRouteImport } from './routes/_authenticated/_app/groups_/join.$inviteCode'
import { Route as AuthenticatedAppGroupsGroupIdSettingsRouteImport } from './routes/_authenticated/_app/groups_/$groupId/settings'
import { Route as AuthenticatedAppGroupsGroupIdMembersRouteImport } from './routes/_authenticated/_app/groups_/$groupId/members'
import { Route as AuthenticatedAppGroupsGroupIdJoinRequestsRouteImport } from './routes/_authenticated/_app/groups_/$groupId/join-requests'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/_onboarding',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/_app',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOnboardingOnboardingRoute =
  AuthenticatedOnboardingOnboardingRouteImport.update({
    id: '/onboarding',
    path: '/onboarding',
    getParentRoute: () => AuthenticatedOnboardingRoute,
  } as any)
const AuthenticatedAppProblemsRoute =
  AuthenticatedAppProblemsRouteImport.update({
    id: '/problems',
    path: '/problems',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppLeaderboardRoute =
  AuthenticatedAppLeaderboardRouteImport.update({
    id: '/leaderboard',
    path: '/leaderboard',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppGroupsRoute = AuthenticatedAppGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppDashboardRoute =
  AuthenticatedAppDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppSettingsBillingRoute =
  AuthenticatedAppSettingsBillingRouteImport.update({
    id: '/settings_/billing',
    path: '/settings/billing',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppGroupsGroupIdRoute =
  AuthenticatedAppGroupsGroupIdRouteImport.update({
    id: '/groups_/$groupId',
    path: '/groups/$groupId',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppGroupsGroupIdIndexRoute =
  AuthenticatedAppGroupsGroupIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppGroupsGroupIdRoute,
  } as any)
const AuthenticatedAppGroupsJoinInviteCodeRoute =
  AuthenticatedAppGroupsJoinInviteCodeRouteImport.update({
    id: '/groups_/join/$inviteCode',
    path: '/groups/join/$inviteCode',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppGroupsGroupIdSettingsRoute =
  AuthenticatedAppGroupsGroupIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAppGroupsGroupIdRoute,
  } as any)
const AuthenticatedAppGroupsGroupIdMembersRoute =
  AuthenticatedAppGroupsGroupIdMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AuthenticatedAppGroupsGroupIdRoute,
  } as any)
const AuthenticatedAppGroupsGroupIdJoinRequestsRoute =
  AuthenticatedAppGroupsGroupIdJoinRequestsRouteImport.update({
    id: '/join-requests',
    path: '/join-requests',
    getParentRoute: () => AuthenticatedAppGroupsGroupIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/$': typeof ApiSplatRoute
  '/dashboard': typeof AuthenticatedAppDashboardRoute
  '/groups': typeof AuthenticatedAppGroupsRoute
  '/leaderboard': typeof AuthenticatedAppLeaderboardRoute
  '/problems': typeof AuthenticatedAppProblemsRoute
  '/onboarding': typeof AuthenticatedOnboardingOnboardingRoute
  '/groups/$groupId': typeof AuthenticatedAppGroupsGroupIdRouteWithChildren
  '/settings/billing': typeof AuthenticatedAppSettingsBillingRoute
  '/groups/$groupId/join-requests': typeof AuthenticatedAppGroupsGroupIdJoinRequestsRoute
  '/groups/$groupId/members': typeof AuthenticatedAppGroupsGroupIdMembersRoute
  '/groups/$groupId/settings': typeof AuthenticatedAppGroupsGroupIdSettingsRoute
  '/groups/join/$inviteCode': typeof AuthenticatedAppGroupsJoinInviteCodeRoute
  '/groups/$groupId/': typeof AuthenticatedAppGroupsGroupIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/$': typeof ApiSplatRoute
  '/dashboard': typeof AuthenticatedAppDashboardRoute
  '/groups': typeof AuthenticatedAppGroupsRoute
  '/leaderboard': typeof AuthenticatedAppLeaderboardRoute
  '/problems': typeof AuthenticatedAppProblemsRoute
  '/onboarding': typeof AuthenticatedOnboardingOnboardingRoute
  '/settings/billing': typeof AuthenticatedAppSettingsBillingRoute
  '/groups/$groupId/join-requests': typeof AuthenticatedAppGroupsGroupIdJoinRequestsRoute
  '/groups/$groupId/members': typeof AuthenticatedAppGroupsGroupIdMembersRoute
  '/groups/$groupId/settings': typeof AuthenticatedAppGroupsGroupIdSettingsRoute
  '/groups/join/$inviteCode': typeof AuthenticatedAppGroupsJoinInviteCodeRoute
  '/groups/$groupId': typeof AuthenticatedAppGroupsGroupIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/_app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/_onboarding': typeof AuthenticatedOnboardingRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/_authenticated/_app/dashboard': typeof AuthenticatedAppDashboardRoute
  '/_authenticated/_app/groups': typeof AuthenticatedAppGroupsRoute
  '/_authenticated/_app/leaderboard': typeof AuthenticatedAppLeaderboardRoute
  '/_authenticated/_app/problems': typeof AuthenticatedAppProblemsRoute
  '/_authenticated/_onboarding/onboarding': typeof AuthenticatedOnboardingOnboardingRoute
  '/_authenticated/_app/groups_/$groupId': typeof AuthenticatedAppGroupsGroupIdRouteWithChildren
  '/_authenticated/_app/settings_/billing': typeof AuthenticatedAppSettingsBillingRoute
  '/_authenticated/_app/groups_/$groupId/join-requests': typeof AuthenticatedAppGroupsGroupIdJoinRequestsRoute
  '/_authenticated/_app/groups_/$groupId/members': typeof AuthenticatedAppGroupsGroupIdMembersRoute
  '/_authenticated/_app/groups_/$groupId/settings': typeof AuthenticatedAppGroupsGroupIdSettingsRoute
  '/_authenticated/_app/groups_/join/$inviteCode': typeof AuthenticatedAppGroupsJoinInviteCodeRoute
  '/_authenticated/_app/groups_/$groupId/': typeof AuthenticatedAppGroupsGroupIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/api/$'
    | '/dashboard'
    | '/groups'
    | '/leaderboard'
    | '/problems'
    | '/onboarding'
    | '/groups/$groupId'
    | '/settings/billing'
    | '/groups/$groupId/join-requests'
    | '/groups/$groupId/members'
    | '/groups/$groupId/settings'
    | '/groups/join/$inviteCode'
    | '/groups/$groupId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/api/$'
    | '/dashboard'
    | '/groups'
    | '/leaderboard'
    | '/problems'
    | '/onboarding'
    | '/settings/billing'
    | '/groups/$groupId/join-requests'
    | '/groups/$groupId/members'
    | '/groups/$groupId/settings'
    | '/groups/join/$inviteCode'
    | '/groups/$groupId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/_app'
    | '/_authenticated/_onboarding'
    | '/api/$'
    | '/_authenticated/_app/dashboard'
    | '/_authenticated/_app/groups'
    | '/_authenticated/_app/leaderboard'
    | '/_authenticated/_app/problems'
    | '/_authenticated/_onboarding/onboarding'
    | '/_authenticated/_app/groups_/$groupId'
    | '/_authenticated/_app/settings_/billing'
    | '/_authenticated/_app/groups_/$groupId/join-requests'
    | '/_authenticated/_app/groups_/$groupId/members'
    | '/_authenticated/_app/groups_/$groupId/settings'
    | '/_authenticated/_app/groups_/join/$inviteCode'
    | '/_authenticated/_app/groups_/$groupId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiSplatRoute: typeof ApiSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_onboarding': {
      id: '/_authenticated/_onboarding'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_app': {
      id: '/_authenticated/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_onboarding/onboarding': {
      id: '/_authenticated/_onboarding/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingOnboardingRouteImport
      parentRoute: typeof AuthenticatedOnboardingRoute
    }
    '/_authenticated/_app/problems': {
      id: '/_authenticated/_app/problems'
      path: '/problems'
      fullPath: '/problems'
      preLoaderRoute: typeof AuthenticatedAppProblemsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/leaderboard': {
      id: '/_authenticated/_app/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AuthenticatedAppLeaderboardRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/groups': {
      id: '/_authenticated/_app/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof AuthenticatedAppGroupsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/dashboard': {
      id: '/_authenticated/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedAppDashboardRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/settings_/billing': {
      id: '/_authenticated/_app/settings_/billing'
      path: '/settings/billing'
      fullPath: '/settings/billing'
      preLoaderRoute: typeof AuthenticatedAppSettingsBillingRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/groups_/$groupId': {
      id: '/_authenticated/_app/groups_/$groupId'
      path: '/groups/$groupId'
      fullPath: '/groups/$groupId'
      preLoaderRoute: typeof AuthenticatedAppGroupsGroupIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/groups_/$groupId/': {
      id: '/_authenticated/_app/groups_/$groupId/'
      path: '/'
      fullPath: '/groups/$groupId/'
      preLoaderRoute: typeof AuthenticatedAppGroupsGroupIdIndexRouteImport
      parentRoute: typeof AuthenticatedAppGroupsGroupIdRoute
    }
    '/_authenticated/_app/groups_/join/$inviteCode': {
      id: '/_authenticated/_app/groups_/join/$inviteCode'
      path: '/groups/join/$inviteCode'
      fullPath: '/groups/join/$inviteCode'
      preLoaderRoute: typeof AuthenticatedAppGroupsJoinInviteCodeRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/groups_/$groupId/settings': {
      id: '/_authenticated/_app/groups_/$groupId/settings'
      path: '/settings'
      fullPath: '/groups/$groupId/settings'
      preLoaderRoute: typeof AuthenticatedAppGroupsGroupIdSettingsRouteImport
      parentRoute: typeof AuthenticatedAppGroupsGroupIdRoute
    }
    '/_authenticated/_app/groups_/$groupId/members': {
      id: '/_authenticated/_app/groups_/$groupId/members'
      path: '/members'
      fullPath: '/groups/$groupId/members'
      preLoaderRoute: typeof AuthenticatedAppGroupsGroupIdMembersRouteImport
      parentRoute: typeof AuthenticatedAppGroupsGroupIdRoute
    }
    '/_authenticated/_app/groups_/$groupId/join-requests': {
      id: '/_authenticated/_app/groups_/$groupId/join-requests'
      path: '/join-requests'
      fullPath: '/groups/$groupId/join-requests'
      preLoaderRoute: typeof AuthenticatedAppGroupsGroupIdJoinRequestsRouteImport
      parentRoute: typeof AuthenticatedAppGroupsGroupIdRoute
    }
  }
}

interface AuthenticatedAppGroupsGroupIdRouteChildren {
  AuthenticatedAppGroupsGroupIdJoinRequestsRoute: typeof AuthenticatedAppGroupsGroupIdJoinRequestsRoute
  AuthenticatedAppGroupsGroupIdMembersRoute: typeof AuthenticatedAppGroupsGroupIdMembersRoute
  AuthenticatedAppGroupsGroupIdSettingsRoute: typeof AuthenticatedAppGroupsGroupIdSettingsRoute
  AuthenticatedAppGroupsGroupIdIndexRoute: typeof AuthenticatedAppGroupsGroupIdIndexRoute
}

const AuthenticatedAppGroupsGroupIdRouteChildren: AuthenticatedAppGroupsGroupIdRouteChildren =
  {
    AuthenticatedAppGroupsGroupIdJoinRequestsRoute:
      AuthenticatedAppGroupsGroupIdJoinRequestsRoute,
    AuthenticatedAppGroupsGroupIdMembersRoute:
      AuthenticatedAppGroupsGroupIdMembersRoute,
    AuthenticatedAppGroupsGroupIdSettingsRoute:
      AuthenticatedAppGroupsGroupIdSettingsRoute,
    AuthenticatedAppGroupsGroupIdIndexRoute:
      AuthenticatedAppGroupsGroupIdIndexRoute,
  }

const AuthenticatedAppGroupsGroupIdRouteWithChildren =
  AuthenticatedAppGroupsGroupIdRoute._addFileChildren(
    AuthenticatedAppGroupsGroupIdRouteChildren,
  )

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppDashboardRoute: typeof AuthenticatedAppDashboardRoute
  AuthenticatedAppGroupsRoute: typeof AuthenticatedAppGroupsRoute
  AuthenticatedAppLeaderboardRoute: typeof AuthenticatedAppLeaderboardRoute
  AuthenticatedAppProblemsRoute: typeof AuthenticatedAppProblemsRoute
  AuthenticatedAppGroupsGroupIdRoute: typeof AuthenticatedAppGroupsGroupIdRouteWithChildren
  AuthenticatedAppSettingsBillingRoute: typeof AuthenticatedAppSettingsBillingRoute
  AuthenticatedAppGroupsJoinInviteCodeRoute: typeof AuthenticatedAppGroupsJoinInviteCodeRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppDashboardRoute: AuthenticatedAppDashboardRoute,
  AuthenticatedAppGroupsRoute: AuthenticatedAppGroupsRoute,
  AuthenticatedAppLeaderboardRoute: AuthenticatedAppLeaderboardRoute,
  AuthenticatedAppProblemsRoute: AuthenticatedAppProblemsRoute,
  AuthenticatedAppGroupsGroupIdRoute:
    AuthenticatedAppGroupsGroupIdRouteWithChildren,
  AuthenticatedAppSettingsBillingRoute: AuthenticatedAppSettingsBillingRoute,
  AuthenticatedAppGroupsJoinInviteCodeRoute:
    AuthenticatedAppGroupsJoinInviteCodeRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedOnboardingRouteChildren {
  AuthenticatedOnboardingOnboardingRoute: typeof AuthenticatedOnboardingOnboardingRoute
}

const AuthenticatedOnboardingRouteChildren: AuthenticatedOnboardingRouteChildren =
  {
    AuthenticatedOnboardingOnboardingRoute:
      AuthenticatedOnboardingOnboardingRoute,
  }

const AuthenticatedOnboardingRouteWithChildren =
  AuthenticatedOnboardingRoute._addFileChildren(
    AuthenticatedOnboardingRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiSplatRoute: ApiSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
