/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProblemsRouteImport } from './routes/problems'
import { Route as LoginRouteImport } from './routes/login'
import { Route as BadgesRouteImport } from './routes/badges'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as UsernameRouteImport } from './routes/$username'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSplatRouteImport } from './routes/api.$'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/_onboarding'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/_app'
import { Route as AuthenticatedOnboardingOnboardingRouteImport } from './routes/_authenticated/_onboarding/onboarding'
import { Route as AuthenticatedAppSettingsRouteImport } from './routes/_authenticated/_app/settings'
import { Route as AuthenticatedAppLeaderboardRouteImport } from './routes/_authenticated/_app/leaderboard'
import { Route as AuthenticatedAppHelpRouteImport } from './routes/_authenticated/_app/help'
import { Route as AuthenticatedAppGroupsRouteImport } from './routes/_authenticated/_app/groups'
import { Route as AuthenticatedAppDashboardRouteImport } from './routes/_authenticated/_app/dashboard'
import { Route as AuthenticatedAppSettingsIndexRouteImport } from './routes/_authenticated/_app/settings/index'
import { Route as AuthenticatedAppSettingsProfileRouteImport } from './routes/_authenticated/_app/settings/profile'
import { Route as AuthenticatedAppSettingsNotificationsRouteImport } from './routes/_authenticated/_app/settings/notifications'
import { Route as AuthenticatedAppSettingsBillingRouteImport } from './routes/_authenticated/_app/settings/billing'
import { Route as AuthenticatedAppSettingsAccountRouteImport } from './routes/_authenticated/_app/settings/account'
import { Route as AuthenticatedAppGroupsGroupIdRouteImport } from './routes/_authenticated/_app/groups_/$groupId'
import { Route as AuthenticatedAppGroupsGroupIdIndexRouteImport } from './routes/_authenticated/_app/groups_/$groupId/index'
import { Route as AuthenticatedAppGroupsJoinInviteCodeRouteImport } from './routes/_authenticated/_app/groups_/join.$inviteCode'
import { Route as AuthenticatedAppGroupsGroupIdSettingsRouteImport } from './routes/_authenticated/_app/groups_/$groupId/settings'
import { Route as AuthenticatedAppGroupsGroupIdMembersRouteImport } from './routes/_authenticated/_app/groups_/$groupId/members'
import { Route as AuthenticatedAppGroupsGroupIdJoinRequestsRouteImport } from './routes/_authenticated/_app/groups_/$groupId/join-requests'

const ProblemsRoute = ProblemsRouteImport.update({
  id: '/problems',
  path: '/problems',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BadgesRoute = BadgesRouteImport.update({
  id: '/badges',
  path: '/badges',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const UsernameRoute = UsernameRouteImport.update({
  id: '/$username',
  path: '/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/_onboarding',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/_app',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOnboardingOnboardingRoute =
  AuthenticatedOnboardingOnboardingRouteImport.update({
    id: '/onboarding',
    path: '/onboarding',
    getParentRoute: () => AuthenticatedOnboardingRoute,
  } as any)
const AuthenticatedAppSettingsRoute =
  AuthenticatedAppSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppLeaderboardRoute =
  AuthenticatedAppLeaderboardRouteImport.update({
    id: '/leaderboard',
    path: '/leaderboard',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppHelpRoute = AuthenticatedAppHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppGroupsRoute = AuthenticatedAppGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppDashboardRoute =
  AuthenticatedAppDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppSettingsIndexRoute =
  AuthenticatedAppSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppSettingsRoute,
  } as any)
const AuthenticatedAppSettingsProfileRoute =
  AuthenticatedAppSettingsProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedAppSettingsRoute,
  } as any)
const AuthenticatedAppSettingsNotificationsRoute =
  AuthenticatedAppSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedAppSettingsRoute,
  } as any)
const AuthenticatedAppSettingsBillingRoute =
  AuthenticatedAppSettingsBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => AuthenticatedAppSettingsRoute,
  } as any)
const AuthenticatedAppSettingsAccountRoute =
  AuthenticatedAppSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedAppSettingsRoute,
  } as any)
const AuthenticatedAppGroupsGroupIdRoute =
  AuthenticatedAppGroupsGroupIdRouteImport.update({
    id: '/groups_/$groupId',
    path: '/groups/$groupId',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppGroupsGroupIdIndexRoute =
  AuthenticatedAppGroupsGroupIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppGroupsGroupIdRoute,
  } as any)
const AuthenticatedAppGroupsJoinInviteCodeRoute =
  AuthenticatedAppGroupsJoinInviteCodeRouteImport.update({
    id: '/groups_/join/$inviteCode',
    path: '/groups/join/$inviteCode',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppGroupsGroupIdSettingsRoute =
  AuthenticatedAppGroupsGroupIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAppGroupsGroupIdRoute,
  } as any)
const AuthenticatedAppGroupsGroupIdMembersRoute =
  AuthenticatedAppGroupsGroupIdMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AuthenticatedAppGroupsGroupIdRoute,
  } as any)
const AuthenticatedAppGroupsGroupIdJoinRequestsRoute =
  AuthenticatedAppGroupsGroupIdJoinRequestsRouteImport.update({
    id: '/join-requests',
    path: '/join-requests',
    getParentRoute: () => AuthenticatedAppGroupsGroupIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$username': typeof UsernameRoute
  '/badges': typeof BadgesRoute
  '/login': typeof LoginRoute
  '/problems': typeof ProblemsRoute
  '/api/$': typeof ApiSplatRoute
  '/dashboard': typeof AuthenticatedAppDashboardRoute
  '/groups': typeof AuthenticatedAppGroupsRoute
  '/help': typeof AuthenticatedAppHelpRoute
  '/leaderboard': typeof AuthenticatedAppLeaderboardRoute
  '/settings': typeof AuthenticatedAppSettingsRouteWithChildren
  '/onboarding': typeof AuthenticatedOnboardingOnboardingRoute
  '/groups/$groupId': typeof AuthenticatedAppGroupsGroupIdRouteWithChildren
  '/settings/account': typeof AuthenticatedAppSettingsAccountRoute
  '/settings/billing': typeof AuthenticatedAppSettingsBillingRoute
  '/settings/notifications': typeof AuthenticatedAppSettingsNotificationsRoute
  '/settings/profile': typeof AuthenticatedAppSettingsProfileRoute
  '/settings/': typeof AuthenticatedAppSettingsIndexRoute
  '/groups/$groupId/join-requests': typeof AuthenticatedAppGroupsGroupIdJoinRequestsRoute
  '/groups/$groupId/members': typeof AuthenticatedAppGroupsGroupIdMembersRoute
  '/groups/$groupId/settings': typeof AuthenticatedAppGroupsGroupIdSettingsRoute
  '/groups/join/$inviteCode': typeof AuthenticatedAppGroupsJoinInviteCodeRoute
  '/groups/$groupId/': typeof AuthenticatedAppGroupsGroupIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$username': typeof UsernameRoute
  '/badges': typeof BadgesRoute
  '/login': typeof LoginRoute
  '/problems': typeof ProblemsRoute
  '/api/$': typeof ApiSplatRoute
  '/dashboard': typeof AuthenticatedAppDashboardRoute
  '/groups': typeof AuthenticatedAppGroupsRoute
  '/help': typeof AuthenticatedAppHelpRoute
  '/leaderboard': typeof AuthenticatedAppLeaderboardRoute
  '/onboarding': typeof AuthenticatedOnboardingOnboardingRoute
  '/settings/account': typeof AuthenticatedAppSettingsAccountRoute
  '/settings/billing': typeof AuthenticatedAppSettingsBillingRoute
  '/settings/notifications': typeof AuthenticatedAppSettingsNotificationsRoute
  '/settings/profile': typeof AuthenticatedAppSettingsProfileRoute
  '/settings': typeof AuthenticatedAppSettingsIndexRoute
  '/groups/$groupId/join-requests': typeof AuthenticatedAppGroupsGroupIdJoinRequestsRoute
  '/groups/$groupId/members': typeof AuthenticatedAppGroupsGroupIdMembersRoute
  '/groups/$groupId/settings': typeof AuthenticatedAppGroupsGroupIdSettingsRoute
  '/groups/join/$inviteCode': typeof AuthenticatedAppGroupsJoinInviteCodeRoute
  '/groups/$groupId': typeof AuthenticatedAppGroupsGroupIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$username': typeof UsernameRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/badges': typeof BadgesRoute
  '/login': typeof LoginRoute
  '/problems': typeof ProblemsRoute
  '/_authenticated/_app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/_onboarding': typeof AuthenticatedOnboardingRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/_authenticated/_app/dashboard': typeof AuthenticatedAppDashboardRoute
  '/_authenticated/_app/groups': typeof AuthenticatedAppGroupsRoute
  '/_authenticated/_app/help': typeof AuthenticatedAppHelpRoute
  '/_authenticated/_app/leaderboard': typeof AuthenticatedAppLeaderboardRoute
  '/_authenticated/_app/settings': typeof AuthenticatedAppSettingsRouteWithChildren
  '/_authenticated/_onboarding/onboarding': typeof AuthenticatedOnboardingOnboardingRoute
  '/_authenticated/_app/groups_/$groupId': typeof AuthenticatedAppGroupsGroupIdRouteWithChildren
  '/_authenticated/_app/settings/account': typeof AuthenticatedAppSettingsAccountRoute
  '/_authenticated/_app/settings/billing': typeof AuthenticatedAppSettingsBillingRoute
  '/_authenticated/_app/settings/notifications': typeof AuthenticatedAppSettingsNotificationsRoute
  '/_authenticated/_app/settings/profile': typeof AuthenticatedAppSettingsProfileRoute
  '/_authenticated/_app/settings/': typeof AuthenticatedAppSettingsIndexRoute
  '/_authenticated/_app/groups_/$groupId/join-requests': typeof AuthenticatedAppGroupsGroupIdJoinRequestsRoute
  '/_authenticated/_app/groups_/$groupId/members': typeof AuthenticatedAppGroupsGroupIdMembersRoute
  '/_authenticated/_app/groups_/$groupId/settings': typeof AuthenticatedAppGroupsGroupIdSettingsRoute
  '/_authenticated/_app/groups_/join/$inviteCode': typeof AuthenticatedAppGroupsJoinInviteCodeRoute
  '/_authenticated/_app/groups_/$groupId/': typeof AuthenticatedAppGroupsGroupIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$username'
    | '/badges'
    | '/login'
    | '/problems'
    | '/api/$'
    | '/dashboard'
    | '/groups'
    | '/help'
    | '/leaderboard'
    | '/settings'
    | '/onboarding'
    | '/groups/$groupId'
    | '/settings/account'
    | '/settings/billing'
    | '/settings/notifications'
    | '/settings/profile'
    | '/settings/'
    | '/groups/$groupId/join-requests'
    | '/groups/$groupId/members'
    | '/groups/$groupId/settings'
    | '/groups/join/$inviteCode'
    | '/groups/$groupId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$username'
    | '/badges'
    | '/login'
    | '/problems'
    | '/api/$'
    | '/dashboard'
    | '/groups'
    | '/help'
    | '/leaderboard'
    | '/onboarding'
    | '/settings/account'
    | '/settings/billing'
    | '/settings/notifications'
    | '/settings/profile'
    | '/settings'
    | '/groups/$groupId/join-requests'
    | '/groups/$groupId/members'
    | '/groups/$groupId/settings'
    | '/groups/join/$inviteCode'
    | '/groups/$groupId'
  id:
    | '__root__'
    | '/'
    | '/$username'
    | '/_authenticated'
    | '/badges'
    | '/login'
    | '/problems'
    | '/_authenticated/_app'
    | '/_authenticated/_onboarding'
    | '/api/$'
    | '/_authenticated/_app/dashboard'
    | '/_authenticated/_app/groups'
    | '/_authenticated/_app/help'
    | '/_authenticated/_app/leaderboard'
    | '/_authenticated/_app/settings'
    | '/_authenticated/_onboarding/onboarding'
    | '/_authenticated/_app/groups_/$groupId'
    | '/_authenticated/_app/settings/account'
    | '/_authenticated/_app/settings/billing'
    | '/_authenticated/_app/settings/notifications'
    | '/_authenticated/_app/settings/profile'
    | '/_authenticated/_app/settings/'
    | '/_authenticated/_app/groups_/$groupId/join-requests'
    | '/_authenticated/_app/groups_/$groupId/members'
    | '/_authenticated/_app/groups_/$groupId/settings'
    | '/_authenticated/_app/groups_/join/$inviteCode'
    | '/_authenticated/_app/groups_/$groupId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UsernameRoute: typeof UsernameRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  BadgesRoute: typeof BadgesRoute
  LoginRoute: typeof LoginRoute
  ProblemsRoute: typeof ProblemsRoute
  ApiSplatRoute: typeof ApiSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/problems': {
      id: '/problems'
      path: '/problems'
      fullPath: '/problems'
      preLoaderRoute: typeof ProblemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/badges': {
      id: '/badges'
      path: '/badges'
      fullPath: '/badges'
      preLoaderRoute: typeof BadgesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$username': {
      id: '/$username'
      path: '/$username'
      fullPath: '/$username'
      preLoaderRoute: typeof UsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_onboarding': {
      id: '/_authenticated/_onboarding'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_app': {
      id: '/_authenticated/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_onboarding/onboarding': {
      id: '/_authenticated/_onboarding/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingOnboardingRouteImport
      parentRoute: typeof AuthenticatedOnboardingRoute
    }
    '/_authenticated/_app/settings': {
      id: '/_authenticated/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedAppSettingsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/leaderboard': {
      id: '/_authenticated/_app/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AuthenticatedAppLeaderboardRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/help': {
      id: '/_authenticated/_app/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof AuthenticatedAppHelpRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/groups': {
      id: '/_authenticated/_app/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof AuthenticatedAppGroupsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/dashboard': {
      id: '/_authenticated/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedAppDashboardRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/settings/': {
      id: '/_authenticated/_app/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedAppSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedAppSettingsRoute
    }
    '/_authenticated/_app/settings/profile': {
      id: '/_authenticated/_app/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof AuthenticatedAppSettingsProfileRouteImport
      parentRoute: typeof AuthenticatedAppSettingsRoute
    }
    '/_authenticated/_app/settings/notifications': {
      id: '/_authenticated/_app/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedAppSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedAppSettingsRoute
    }
    '/_authenticated/_app/settings/billing': {
      id: '/_authenticated/_app/settings/billing'
      path: '/billing'
      fullPath: '/settings/billing'
      preLoaderRoute: typeof AuthenticatedAppSettingsBillingRouteImport
      parentRoute: typeof AuthenticatedAppSettingsRoute
    }
    '/_authenticated/_app/settings/account': {
      id: '/_authenticated/_app/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedAppSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedAppSettingsRoute
    }
    '/_authenticated/_app/groups_/$groupId': {
      id: '/_authenticated/_app/groups_/$groupId'
      path: '/groups/$groupId'
      fullPath: '/groups/$groupId'
      preLoaderRoute: typeof AuthenticatedAppGroupsGroupIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/groups_/$groupId/': {
      id: '/_authenticated/_app/groups_/$groupId/'
      path: '/'
      fullPath: '/groups/$groupId/'
      preLoaderRoute: typeof AuthenticatedAppGroupsGroupIdIndexRouteImport
      parentRoute: typeof AuthenticatedAppGroupsGroupIdRoute
    }
    '/_authenticated/_app/groups_/join/$inviteCode': {
      id: '/_authenticated/_app/groups_/join/$inviteCode'
      path: '/groups/join/$inviteCode'
      fullPath: '/groups/join/$inviteCode'
      preLoaderRoute: typeof AuthenticatedAppGroupsJoinInviteCodeRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/groups_/$groupId/settings': {
      id: '/_authenticated/_app/groups_/$groupId/settings'
      path: '/settings'
      fullPath: '/groups/$groupId/settings'
      preLoaderRoute: typeof AuthenticatedAppGroupsGroupIdSettingsRouteImport
      parentRoute: typeof AuthenticatedAppGroupsGroupIdRoute
    }
    '/_authenticated/_app/groups_/$groupId/members': {
      id: '/_authenticated/_app/groups_/$groupId/members'
      path: '/members'
      fullPath: '/groups/$groupId/members'
      preLoaderRoute: typeof AuthenticatedAppGroupsGroupIdMembersRouteImport
      parentRoute: typeof AuthenticatedAppGroupsGroupIdRoute
    }
    '/_authenticated/_app/groups_/$groupId/join-requests': {
      id: '/_authenticated/_app/groups_/$groupId/join-requests'
      path: '/join-requests'
      fullPath: '/groups/$groupId/join-requests'
      preLoaderRoute: typeof AuthenticatedAppGroupsGroupIdJoinRequestsRouteImport
      parentRoute: typeof AuthenticatedAppGroupsGroupIdRoute
    }
  }
}

interface AuthenticatedAppSettingsRouteChildren {
  AuthenticatedAppSettingsAccountRoute: typeof AuthenticatedAppSettingsAccountRoute
  AuthenticatedAppSettingsBillingRoute: typeof AuthenticatedAppSettingsBillingRoute
  AuthenticatedAppSettingsNotificationsRoute: typeof AuthenticatedAppSettingsNotificationsRoute
  AuthenticatedAppSettingsProfileRoute: typeof AuthenticatedAppSettingsProfileRoute
  AuthenticatedAppSettingsIndexRoute: typeof AuthenticatedAppSettingsIndexRoute
}

const AuthenticatedAppSettingsRouteChildren: AuthenticatedAppSettingsRouteChildren =
  {
    AuthenticatedAppSettingsAccountRoute: AuthenticatedAppSettingsAccountRoute,
    AuthenticatedAppSettingsBillingRoute: AuthenticatedAppSettingsBillingRoute,
    AuthenticatedAppSettingsNotificationsRoute:
      AuthenticatedAppSettingsNotificationsRoute,
    AuthenticatedAppSettingsProfileRoute: AuthenticatedAppSettingsProfileRoute,
    AuthenticatedAppSettingsIndexRoute: AuthenticatedAppSettingsIndexRoute,
  }

const AuthenticatedAppSettingsRouteWithChildren =
  AuthenticatedAppSettingsRoute._addFileChildren(
    AuthenticatedAppSettingsRouteChildren,
  )

interface AuthenticatedAppGroupsGroupIdRouteChildren {
  AuthenticatedAppGroupsGroupIdJoinRequestsRoute: typeof AuthenticatedAppGroupsGroupIdJoinRequestsRoute
  AuthenticatedAppGroupsGroupIdMembersRoute: typeof AuthenticatedAppGroupsGroupIdMembersRoute
  AuthenticatedAppGroupsGroupIdSettingsRoute: typeof AuthenticatedAppGroupsGroupIdSettingsRoute
  AuthenticatedAppGroupsGroupIdIndexRoute: typeof AuthenticatedAppGroupsGroupIdIndexRoute
}

const AuthenticatedAppGroupsGroupIdRouteChildren: AuthenticatedAppGroupsGroupIdRouteChildren =
  {
    AuthenticatedAppGroupsGroupIdJoinRequestsRoute:
      AuthenticatedAppGroupsGroupIdJoinRequestsRoute,
    AuthenticatedAppGroupsGroupIdMembersRoute:
      AuthenticatedAppGroupsGroupIdMembersRoute,
    AuthenticatedAppGroupsGroupIdSettingsRoute:
      AuthenticatedAppGroupsGroupIdSettingsRoute,
    AuthenticatedAppGroupsGroupIdIndexRoute:
      AuthenticatedAppGroupsGroupIdIndexRoute,
  }

const AuthenticatedAppGroupsGroupIdRouteWithChildren =
  AuthenticatedAppGroupsGroupIdRoute._addFileChildren(
    AuthenticatedAppGroupsGroupIdRouteChildren,
  )

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppDashboardRoute: typeof AuthenticatedAppDashboardRoute
  AuthenticatedAppGroupsRoute: typeof AuthenticatedAppGroupsRoute
  AuthenticatedAppHelpRoute: typeof AuthenticatedAppHelpRoute
  AuthenticatedAppLeaderboardRoute: typeof AuthenticatedAppLeaderboardRoute
  AuthenticatedAppSettingsRoute: typeof AuthenticatedAppSettingsRouteWithChildren
  AuthenticatedAppGroupsGroupIdRoute: typeof AuthenticatedAppGroupsGroupIdRouteWithChildren
  AuthenticatedAppGroupsJoinInviteCodeRoute: typeof AuthenticatedAppGroupsJoinInviteCodeRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppDashboardRoute: AuthenticatedAppDashboardRoute,
  AuthenticatedAppGroupsRoute: AuthenticatedAppGroupsRoute,
  AuthenticatedAppHelpRoute: AuthenticatedAppHelpRoute,
  AuthenticatedAppLeaderboardRoute: AuthenticatedAppLeaderboardRoute,
  AuthenticatedAppSettingsRoute: AuthenticatedAppSettingsRouteWithChildren,
  AuthenticatedAppGroupsGroupIdRoute:
    AuthenticatedAppGroupsGroupIdRouteWithChildren,
  AuthenticatedAppGroupsJoinInviteCodeRoute:
    AuthenticatedAppGroupsJoinInviteCodeRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedOnboardingRouteChildren {
  AuthenticatedOnboardingOnboardingRoute: typeof AuthenticatedOnboardingOnboardingRoute
}

const AuthenticatedOnboardingRouteChildren: AuthenticatedOnboardingRouteChildren =
  {
    AuthenticatedOnboardingOnboardingRoute:
      AuthenticatedOnboardingOnboardingRoute,
  }

const AuthenticatedOnboardingRouteWithChildren =
  AuthenticatedOnboardingRoute._addFileChildren(
    AuthenticatedOnboardingRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UsernameRoute: UsernameRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  BadgesRoute: BadgesRoute,
  LoginRoute: LoginRoute,
  ProblemsRoute: ProblemsRoute,
  ApiSplatRoute: ApiSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
